//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDoxa.Notifications.Api.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eDoxa.Notifications.Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something failed when attempting to delete this notification &apos;{0}&apos; for the recipient &apos;{1}&apos;..
        /// </summary>
        public static string NotificationsController_BadRequest_DeleteNotificationAsync {
            get {
                return ResourceManager.GetString("NotificationsController_BadRequest_DeleteNotificationAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something failed when attempting to read this notification &apos;{0}&apos; for the recipient &apos;{1}&apos;..
        /// </summary>
        public static string NotificationsController_BadRequest_ReadNotificationAsync {
            get {
                return ResourceManager.GetString("NotificationsController_BadRequest_ReadNotificationAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something failed when attempting to delete this notification &apos;{0}&apos; for the recipient &apos;{1}&apos;..
        /// </summary>
        public static string NotificationsController_Error_DeleteNotificationAsync {
            get {
                return ResourceManager.GetString("NotificationsController_Error_DeleteNotificationAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something failed when attempting to read this notification &apos;{0}&apos; for the recipient &apos;{1}&apos;..
        /// </summary>
        public static string NotificationsController_Error_ReadNotificationAsync {
            get {
                return ResourceManager.GetString("NotificationsController_Error_ReadNotificationAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NotificationsController_NotFound_DeleteNotificationAsync {
            get {
                return ResourceManager.GetString("NotificationsController_NotFound_DeleteNotificationAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NotificationsController_NotFound_ReadNotificationAsync {
            get {
                return ResourceManager.GetString("NotificationsController_NotFound_ReadNotificationAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NotificationsController_Ok_DeleteNotificationAsync {
            get {
                return ResourceManager.GetString("NotificationsController_Ok_DeleteNotificationAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NotificationsController_Ok_ReadNotificationAsync {
            get {
                return ResourceManager.GetString("NotificationsController_Ok_ReadNotificationAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserNotificationsController_BadRequest_CountUserNotificationsAsync {
            get {
                return ResourceManager.GetString("UserNotificationsController_BadRequest_CountUserNotificationsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something failed when attempting to fetch notifications for the user &apos;{0}&apos;..
        /// </summary>
        public static string UserNotificationsController_BadRequest_FetchUserNotificationsAsync {
            get {
                return ResourceManager.GetString("UserNotificationsController_BadRequest_FetchUserNotificationsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something failed when attempting to find this notification &apos;{0}&apos; for the user &apos;{1}&apos;..
        /// </summary>
        public static string UserNotificationsController_BadRequest_FindUserNotificationAsync {
            get {
                return ResourceManager.GetString("UserNotificationsController_BadRequest_FindUserNotificationAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserNotificationsController_Error_CountUserNotificationsAsync {
            get {
                return ResourceManager.GetString("UserNotificationsController_Error_CountUserNotificationsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something failed when attempting to fetch notifications for the user &apos;{0}&apos;..
        /// </summary>
        public static string UserNotificationsController_Error_FetchUserNotificationsAsync {
            get {
                return ResourceManager.GetString("UserNotificationsController_Error_FetchUserNotificationsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something failed when attempting to find this notification &apos;{0}&apos; for the user &apos;{1}&apos;..
        /// </summary>
        public static string UserNotificationsController_Error_FindUserNotificationAsync {
            get {
                return ResourceManager.GetString("UserNotificationsController_Error_FindUserNotificationAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserNotificationsController_NotFound_CountUserNotificationsAsync {
            get {
                return ResourceManager.GetString("UserNotificationsController_NotFound_CountUserNotificationsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserNotificationsController_NotFound_FetchUserNotificationsAsync {
            get {
                return ResourceManager.GetString("UserNotificationsController_NotFound_FetchUserNotificationsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserNotificationsController_NotFound_FindUserNotificationAsync {
            get {
                return ResourceManager.GetString("UserNotificationsController_NotFound_FindUserNotificationAsync", resourceCulture);
            }
        }
    }
}
