apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tracing-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 15032
        name: https-tracing
        protocol: HTTPS
      tls:
        mode: SIMPLE
        serverCertificate: sds
        privateKey: sds
        credentialName: telemetry-gw-cert
      hosts:
        - "telemetry.edoxa.gg"
