//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDoxa.Notifications.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eDoxa.Notifications.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The challenge {0} was closed..
        /// </summary>
        internal static string NotificationDescription_ChallengeClosed_Template {
            get {
                return ResourceManager.GetString("NotificationDescription_ChallengeClosed_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge closed.
        /// </summary>
        internal static string NotificationDescription_ChallengeClosed_Title {
            get {
                return ResourceManager.GetString("NotificationDescription_ChallengeClosed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prizes of the challenge {0} have been distributed to participants..
        /// </summary>
        internal static string NotificationDescription_ChallengeParticipantPaid_Template {
            get {
                return ResourceManager.GetString("NotificationDescription_ChallengeParticipantPaid_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant paid.
        /// </summary>
        internal static string NotificationDescription_ChallengeParticipantPaid_Title {
            get {
                return ResourceManager.GetString("NotificationDescription_ChallengeParticipantPaid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have registered to the challenge {0}..
        /// </summary>
        internal static string NotificationDescription_ChallengeParticipantRegistered_Template {
            get {
                return ResourceManager.GetString("NotificationDescription_ChallengeParticipantRegistered_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant registered.
        /// </summary>
        internal static string NotificationDescription_ChallengeParticipantRegistered_Title {
            get {
                return ResourceManager.GetString("NotificationDescription_ChallengeParticipantRegistered_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New challenges was published..
        /// </summary>
        internal static string NotificationDescription_ChallengePublished_Template {
            get {
                return ResourceManager.GetString("NotificationDescription_ChallengePublished_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenges published.
        /// </summary>
        internal static string NotificationDescription_ChallengePublished_Title {
            get {
                return ResourceManager.GetString("NotificationDescription_ChallengePublished_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email was updated for {0}..
        /// </summary>
        internal static string NotificationDescription_UserEmailUpdated_Template {
            get {
                return ResourceManager.GetString("NotificationDescription_UserEmailUpdated_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email updated.
        /// </summary>
        internal static string NotificationDescription_UserEmailUpdated_Title {
            get {
                return ResourceManager.GetString("NotificationDescription_UserEmailUpdated_Title", resourceCulture);
            }
        }
    }
}
