version: '3.7'

services:
  mssql.integration-tests:
    image: microsoft/mssql-server-linux:latest

  redis.integration-tests:
    image: redis:latest

  rabbitmq.integration-tests:
    image: rabbitmq:latest

  identity.integration-tests:
    image: ${ACR_REGISTRY:-edoxa}/identity.integration-tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: test/eDoxa.Identity.IntegrationTests/Dockerfile
    entrypoint: dotnet test --logger:trx;LogFileName=/var/tmp/eDoxa.Identity.IntegrationTestResults.trx
    volumes:
      - ${BUILD_ARTIFACTDIRECTORY:-.}/vsts/test/results:/var/tmp   
    depends_on:
      - mssql.integration-tests
      - redis.integration-tests
      - rabbitmq.integration-tests

  cashier.integration-tests:
    image: ${ACR_REGISTRY:-edoxa}/cashier.integration-tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: test/eDoxa.Cashier.IntegrationTests/Dockerfile
    entrypoint: dotnet test --logger:trx;LogFileName=/var/tmp/eDoxa.Cashier.IntegrationTestResults.trx
    volumes:
      - ${BUILD_ARTIFACTDIRECTORY:-.}/vsts/test/results:/var/tmp   
    depends_on:
      - mssql.integration-tests
      - redis.integration-tests
      - rabbitmq.integration-tests

  arena.challenges.integration-tests:
    image: ${ACR_REGISTRY:-edoxa}/arena.challenges.integration-tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: test/eDoxa.Arena.Challenges.IntegrationTests/Dockerfile
    entrypoint: dotnet test --logger:trx;LogFileName=/var/tmp/eDoxa.Arena.Challenges.IntegrationTestResults.trx
    volumes:
      - ${BUILD_ARTIFACTDIRECTORY:-.}/vsts/test/results:/var/tmp   
    depends_on:
      - mssql.integration-tests
      - redis.integration-tests
      - rabbitmq.integration-tests