version: '3.7'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-CU14-ubuntu

  redis:
    image: redis:5.0.5

  rabbitmq:
    image: rabbitmq:3-management-alpine

  seq:
    image: datalust/seq:latest

  identity-api:
    image: ${ACR_REGISTRY:-edoxa}/dev/identity-api:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Identity.Api/Dockerfile
    depends_on:
      - seq
      - mssql
      - redis

  cashier-api:
    image: ${ACR_REGISTRY:-edoxa}/dev/cashier-api:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Cashier.Api/Dockerfile
    depends_on:
      - seq
      - mssql
      - identity-api

  challenges-api:
    image: ${ACR_REGISTRY:-edoxa}/dev/challenges-api:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Challenges.Api/Dockerfile
    depends_on:
      - seq   
      - mssql
      - identity-api
      - cashier-api
      - games-api

  clans-api:
    image: ${ACR_REGISTRY:-edoxa}/dev/clans-api:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Clans.Api/Dockerfile
    depends_on:
      - seq
      - mssql
      - identity-api

  games-api:
    image: ${ACR_REGISTRY:-edoxa}/dev/games-api:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Games.Api/Dockerfile
    depends_on:
      - seq
      - mssql
      - redis
      - identity-api

  notifications-api:
    image: ${ACR_REGISTRY:-edoxa}/dev/notifications-api:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Notifications.Api/Dockerfile
    depends_on:
      - seq      
      - mssql
      - identity-api

  payment-api:
    image: ${ACR_REGISTRY:-edoxa}/dev/payment-api:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Payment.Api/Dockerfile
    depends_on:
      - seq
      - mssql
      - identity-api

  challenges-worker:
    image: ${ACR_REGISTRY:-edoxa}/dev/challenges-worker:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Challenges.Worker/Dockerfile
    depends_on:
      - seq
      - challenges-api
      - games-api

  cashier-web-aggregator:
    image: ${ACR_REGISTRY:-edoxa}/dev/cashier-web-aggregator:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Cashier.Web.Aggregator/Dockerfile
    depends_on:
      - seq   
      - identity-api
      - payment-api
      - cashier-api

  challenges-web-aggregator:
    image: ${ACR_REGISTRY:-edoxa}/dev/challenges-web-aggregator:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Challenges.Web.Aggregator/Dockerfile
    depends_on:
      - seq   
      - identity-api
      - cashier-api
      - games-api
      - challenges-api

  cashier-web-gateway:
    image: envoyproxy/envoy:v1.11.1

  challenges-web-gateway:
    image: envoyproxy/envoy:v1.11.1

  web-spa:
    image: ${ACR_REGISTRY:-edoxa}/dev/web-spa:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Web.Spa/Dockerfile
    depends_on:
      - seq
      - redis
      - identity-api
      - cashier-web-gateway
      - challenges-web-gateway

  web-status:
    image: ${ACR_REGISTRY:-edoxa}/dev/web-status:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Web.Status/Dockerfile
    depends_on:
      - seq