version: '3.7'

services:
  mssql:
    environment:
      - SA_PASSWORD=fnU3Www9TnBDp3MA
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"

  redis:
    ports:
      - "6379:6379"

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5400:80"

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ApplicationInsights__InstrumentationKey=47ce723c-52e7-4714-931a-19e72c037c9a
      - ConnectionStrings__SqlServer=${MSSQL_IDENTITY:-Server=mssql;Database=Services.Identity;User Id=sa;Password=fnU3Www9TnBDp3MA}
      - ConnectionStrings__Redis=${REDIS:-redis}
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - AzureServiceBusEnabled=${ASB_ENABLE:-false}
      - ServiceBus__HostName=${ASB_HOSTNAME:-rabbitmq}
      - ServiceBus__SubscriptionName=identity
      - AzureKubernetesServiceEnabled=${AKS_ENABLE:-false}
      - Authority__PrivateUrl=http://identity.api
      - Authority__PublicUrl=http://${HOST:-localhost}:5000
      - IdentityServer__IdentityUrl=http://${HOST:-localhost}:5000
      - IdentityServer__CashierUrl=http://${HOST:-localhost}:5002
      - IdentityServer__ArenaChallengesUrl=http://${HOST:-localhost}:5003
      - IdentityServer__Web__SpaUrl=http://${HOST:-localhost}:5300
    ports:
      - "5000:80"

  payment.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ApplicationInsights__InstrumentationKey=47ce723c-52e7-4714-931a-19e72c037c9a
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}      
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - AzureServiceBusEnabled=${ASB_ENABLE:-false}
      - ServiceBus__HostName=${ASB_HOSTNAME:-rabbitmq}
      - ServiceBus__SubscriptionName=payment
    ports:
      - "5001:80"

  cashier.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ApplicationInsights__InstrumentationKey=47ce723c-52e7-4714-931a-19e72c037c9a
      - ConnectionStrings__SqlServer=${MSSQL_CASHIER:-Server=mssql;Database=Services.Cashier;User Id=sa;Password=fnU3Www9TnBDp3MA}
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}      
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - AzureServiceBusEnabled=${ASB_ENABLE:-false}
      - ServiceBus__HostName=${ASB_HOSTNAME:-rabbitmq}
      - ServiceBus__SubscriptionName=cashier
      - HealthChecks__PaymentUrl=http://payment.api/health
      - Authority__PrivateUrl=http://identity.api
      - Authority__PublicUrl=http://${HOST:-localhost}:5000      
    ports:
      - "5002:80"

  arena.challenges.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ApplicationInsights__InstrumentationKey=47ce723c-52e7-4714-931a-19e72c037c9a
      - ConnectionStrings__SqlServer=${MSSQL_CHALLENGE:-Server=mssql;Database=Services.Arena.Challenges;User Id=sa;Password=fnU3Www9TnBDp3MA}      
      - ConnectionStrings__Redis=${REDIS:-redis}
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - AzureServiceBusEnabled=${ASB_ENABLE:-false}
      - ServiceBus__HostName=${ASB_HOSTNAME:-rabbitmq}
      - ServiceBus__SubscriptionName=arena.challenges
      - Authority__PrivateUrl=http://identity.api
      - Authority__PublicUrl=http://${HOST:-localhost}:5000      
    ports:
      - "5003:80"

  web.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ApplicationInsights__InstrumentationKey=47ce723c-52e7-4714-931a-19e72c037c9a
      - HealthChecks__IdentityUrl=http://identity.api/health
      - HealthChecks__CashierUrl=http://cashier.api/health
      - HealthChecks__ArenaChallengesUrl=http://arena.challenges.api/health      
      - Authority__PrivateUrl=http://identity.api
      - Authority__PublicUrl=http://${HOST:-localhost}:5000
    ports:
      - "5200:80"
    volumes:
      - ./src/eDoxa.Web.Gateway:/app

  web.spa.proxy:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ApplicationInsights__InstrumentationKey=47ce723c-52e7-4714-931a-19e72c037c9a
      - ConnectionStrings__Redis=${REDIS:-redis}
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - AzureKubernetesServiceEnabled=${AKS_ENABLE:-false}
      - Authority__PublicUrl=http://${HOST:-localhost}:5000
      - Authority__PrivateUrl=http://identity.api
      - Web__GatewayUrl=http://${HOST:-localhost}:5200
      - Web__ClientUrl=http://${HOST:-localhost}:3000
      - HealthChecks__Web__GatewayUrl=http://web.gateway/health
    ports:
      - "5300:80"

  web.spa.client:
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_AUTHORITY=http://${HOST:-localhost}:5000
      - REACT_APP_REDIRECT_URI=http://${HOST:-localhost}:5300/callback
      - REACT_APP_CLIENT_ID=edoxa.web.spa
      - REACT_APP_RESPONSE_TYPE=token id_token
      - REACT_APP_SCOPE=openid profile roles permissions games stripe identity.api cashier.api arena.challenges.api
      - REACT_APP_WEB_GATEWAY=http://${HOST:-localhost}:5200
      - REACT_APP_SILENT_REFRESH_URI=http://${HOST:-localhost}:5300/silent-refresh
      - REACT_APP_STRIPE_APIKEY=sk_test_xRMH8A7bagp2Auj7YPqNihlY
      - REACT_APP_LEAGUEOFLEGENDS_RIOT_TOKEN=RGAPI-eb72733e-028a-4bb9-ab4d-63fed558924f
    volumes:
      - './src/eDoxa.Web.Spa/ClientApp:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'

  web.status:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ApplicationInsights__InstrumentationKey=47ce723c-52e7-4714-931a-19e72c037c9a
      - HealthChecks__Endpoints__0__Name=eDoxa Identity API
      - HealthChecks__Endpoints__0__Uri=http://identity.api/health
      - HealthChecks__Endpoints__1__Name=eDoxa Payment API
      - HealthChecks__Endpoints__1__Uri=http://payment.api/health
      - HealthChecks__Endpoints__2__Name=eDoxa Cashier API
      - HealthChecks__Endpoints__2__Uri=http://cashier.api/health
      - HealthChecks__Endpoints__3__Name=eDoxa Arena Challenges API
      - HealthChecks__Endpoints__3__Uri=http://arena.challenges.api/health
      - HealthChecks__Endpoints__4__Name=eDoxa Web Gateway
      - HealthChecks__Endpoints__4__Uri=http://web.gateway/health
      - HealthChecks__Endpoints__5__Name=eDoxa Web Spa
      - HealthChecks__Endpoints__5__Uri=http://web.spa.proxy/health
      - HealthChecks__EvaluationTimeInSeconds=60
      - HealthChecks__MinimumSecondsBetweenFailureNotifications=300
    ports:
      - "5500:80"