version: '3.4'

services:
  edoxa.mssql.data:
    image: microsoft/mssql-server-linux:latest

  edoxa.redis.data:
    image: redis:latest

  edoxa.rabbitmq.broker:
    image: rabbitmq:latest

  edoxa.identity:
    image: $ACR_REGISTRY/identity:$ACR_TAG
    build:
      context: .
      dockerfile: src/eDoxa.Identity/Dockerfile
    depends_on:
      - edoxa.mssql.data
      - edoxa.redis.data
      - edoxa.rabbitmq.broker 

  edoxa.challenges.api:
    image: $ACR_REGISTRY/challenges.api:$ACR_TAG
    build:
      context: .
      dockerfile: src/eDoxa.Challenges.Api/Dockerfile
    depends_on:
      - edoxa.mssql.data
      - edoxa.rabbitmq.broker 
      - edoxa.identity

  edoxa.cashier.api:
    image: $ACR_REGISTRY/cashier.api:$ACR_TAG
    build:
      context: .
      dockerfile: src/eDoxa.Cashier.Api/Dockerfile
    depends_on:
      - edoxa.mssql.data
      - edoxa.rabbitmq.broker 
      - edoxa.identity

  #edoxa.web.spa:
  #  image: $ACR_REGISTRY/web.spa:$ACR_TAG
  #  build:
  #    context: .
  #    dockerfile: src/eDoxa.Web.Spa/Dockerfile

  edoxa.web.status:
    image: $ACR_REGISTRY/web.status:$ACR_TAG
    build:
      context: .
      dockerfile: src/eDoxa.Web.Status/Dockerfile