version: '3.4'

services:
  edoxa.mssql.data:
    image: microsoft/mssql-server-linux:latest

  edoxa.redis.data:
    image: redis:latest

  edoxa.rabbitmq.broker:
    image: rabbitmq:latest

  edoxa.identity:
    image: $DOCKER_REGISTRY/identity:$DOCKER_TAG
    build:
      context: .
      dockerfile: src/eDoxa.Identity/Dockerfile
    depends_on:
      - edoxa.mssql.data
      - edoxa.redis.data
      - edoxa.rabbitmq.broker 

  edoxa.challenges.api:
    image: $DOCKER_REGISTRY/challenges.api:$DOCKER_TAG
    build:
      context: .
      dockerfile: src/eDoxa.Challenges.Api/Dockerfile
    depends_on:
      - edoxa.mssql.data
      - edoxa.rabbitmq.broker 
      - edoxa.identity

  edoxa.cashier.api:
    image: $DOCKER_REGISTRY/cashier.api:$DOCKER_TAG
    build:
      context: .
      dockerfile: src/eDoxa.Cashier.Api/Dockerfile
    depends_on:
      - edoxa.mssql.data
      - edoxa.rabbitmq.broker 
      - edoxa.identity

  edoxa.notifications.api:
    image: $DOCKER_REGISTRY/notifications.api:$DOCKER_TAG
    build:
      context: .
      dockerfile: src/eDoxa.Notifications.Api/Dockerfile
    depends_on:
      - edoxa.mssql.data
      - edoxa.rabbitmq.broker 
      - edoxa.identity

  edoxa.challenges.backgroundtasks:
    image: $DOCKER_REGISTRY/challenges.backgroundtasks:$DOCKER_TAG
    build:
      context: .
      dockerfile: src/eDoxa.Challenges.BackgroundTasks/Dockerfile
    depends_on:
      - edoxa.mssql.data
      - edoxa.rabbitmq.broker 
      - edoxa.challenges.api

  #edoxa.web.spa:
  #  image: $DOCKER_REGISTRY/web.spa:$DOCKER_TAG
  #  build:
  #    context: .
  #    dockerfile: src/eDoxa.Web.Spa/Dockerfile

  edoxa.web.status:
    image: $DOCKER_REGISTRY/web.status:$DOCKER_TAG
    build:
      context: .
      dockerfile: src/eDoxa.Web.Status/Dockerfile