version: '3.7'

services:
  mssql:
    environment:
      - SA_PASSWORD=fnU3Www9TnBDp3MA
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"

  redis:
    ports:
      - "6379:6379"

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__SqlServer=${MSSQL_IDENTITY:-Server=mssql;Database=Services.Identity;User Id=sa;Password=fnU3Www9TnBDp3MA}
      - ConnectionStrings__Redis=${REDIS:-redis}
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - AzureServiceBus__Enable=${ASB_ENABLE:-false}
      - ServiceBus__HostName=${ASB_HOSTNAME:-rabbitmq}
      - ServiceBus__RetryCount=${ASB_RETRYCOUNT:-5}
      - ServiceBus__Subscription=Identity
      - AzureKubernetesService__Enable=${AKS_ENABLE:-false}
      - Authority=${URL:-http://localhost}:5000
      - Identity__Url=${URL:-http://localhost}:5000
      - Cashier__Url=${URL:-http://localhost}:5002
      - Challenge__Url=${URL:-http://localhost}:5003
      - Web__Spa__Url=${URL:-http://localhost}:5300
      - IdentityServer__Url=http://identity.api
    ports:
      - "5000:80"
    volumes:
      - ./data/Identity/SourceFiles:/app/Infrastructure/Data/Storage/SourceFiles
      - ./data/Identity/TestFiles:/app/Infrastructure/Data/Storage/TestFiles

  cashier.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__SqlServer=${MSSQL_CASHIER:-Server=mssql;Database=Services.Cashier;User Id=sa;Password=fnU3Www9TnBDp3MA}
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}      
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - AzureServiceBus__Enable=${ASB_ENABLE:-false}
      - ServiceBus__HostName=${ASB_HOSTNAME:-rabbitmq}
      - ServiceBus__RetryCount=${ASB_RETRYCOUNT:-5}
      - ServiceBus__Subscription=Cashier
      - HealthChecks__Payment__Url=http://payment.api/health
      - Authority=${URL:-http://localhost}:5000
      - IdentityServer__Url=http://identity.api
    ports:
      - "5002:80"
    volumes:
      - ./data/Cashier/SourceFiles:/app/Infrastructure/Data/Storage/SourceFiles
      - ./data/Cashier/TestFiles:/app/Infrastructure/Data/Storage/TestFiles

  arena.challenges.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__SqlServer=${MSSQL_CHALLENGE:-Server=mssql;Database=Services.Arena.Challenges;User Id=sa;Password=fnU3Www9TnBDp3MA}      
      - ConnectionStrings__Redis=${REDIS:-redis}
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - AzureServiceBus__Enable=${ASB_ENABLE:-false}
      - ServiceBus__HostName=${ASB_HOSTNAME:-rabbitmq}
      - ServiceBus__RetryCount=${ASB_RETRYCOUNT:-5}
      - ServiceBus__Subscription=Arena.Challenges
      - Authority=${URL:-http://localhost}:5000
      - IdentityServer__Url=http://identity.api
    ports:
      - "5003:80"
    volumes:
      - ./data/Arena/Challenges/SourceFiles:/app/Infrastructure/Data/Storage/SourceFiles
      - ./data/Arena/Challenges/TestFiles:/app/Infrastructure/Data/Storage/TestFiles

  payment.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}      
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - AzureServiceBus__Enable=${ASB_ENABLE:-false}
      - ServiceBus__HostName=${ASB_HOSTNAME:-rabbitmq}
      - ServiceBus__RetryCount=${ASB_RETRYCOUNT:-5}
      - ServiceBus__Subscription=Payment
    ports:
      - "5004:80"

  web.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
      - HealthChecks__Identity__Url=http://identity.api/health
      - HealthChecks__Cashier__Url=http://cashier.api/health
      - HealthChecks__ArenaChallenges__Url=http://arena.challenges.api/health
      - IdentityServer__Url=http://identity.api
    ports:
      - "5200:80"
    volumes:
      - ./api/eDoxa.Web.Gateway:/app/ocelot

  #web.spa:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=http://+:80
  #    - ConnectionStrings__Redis=${REDIS:-redis}
  #    - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
  #    - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
  #    - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
  #    - AzureKubernetesService__Enable=${AKS_ENABLE:-false}
  #    - Authority=${URL:-http://localhost}:5000  
  #    - IdentityServer__Url=${URL:-http://localhost}:5000
  #    - Identity__Url=${URL:-http://localhost}:5001
  #    - Cashier__Url=${URL:-http://localhost}:5002
  #    - Challenge__Url=${URL:-http://localhost}:5003
  #    - WebSpa__Url=${URL:-http://localhost}:5300
  #  ports:
  #    - "5300:80"

  web.status:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - HealthChecks__Endpoints__0__Name=eDoxa Identity API
      - HealthChecks__Endpoints__0__Uri=http://identity.api/health
      - HealthChecks__Endpoints__1__Name=eDoxa Cashier API
      - HealthChecks__Endpoints__1__Uri=http://cashier.api/health
      - HealthChecks__Endpoints__2__Name=eDoxa Payment API
      - HealthChecks__Endpoints__2__Uri=http://payment.api/health
      - HealthChecks__Endpoints__3__Name=eDoxa Arena Challenges API
      - HealthChecks__Endpoints__3__Uri=http://arena.challenges.api/health
      - HealthChecks__Endpoints__4__Name=eDoxa Web Gateway
      - HealthChecks__Endpoints__4__Uri=http://web.gateway/health
      - HealthChecks__Endpoints__5__Name=eDoxa Web Spa
      - HealthChecks__Endpoints__5__Uri=http://web.spa/health
      - HealthChecks__EvaluationTimeInSeconds=15
      - HealthChecks__MinimumSecondsBetweenFailureNotifications=60
    ports:
      - "5500:80"