version: '3.7'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-CU14-ubuntu

  redis:
    image: redis:5.0.5

  rabbitmq:
    image: rabbitmq:3-management

  seq:
    image: datalust/seq:latest

  identity.api:
    image: ${ACR_REGISTRY:-edoxa}/identity.api:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Identity.Api/Dockerfile
    depends_on:
      - seq
      - mssql
      - redis
      - rabbitmq

  cashier.api:
    image: ${ACR_REGISTRY:-edoxa}/cashier.api:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Cashier.Api/Dockerfile
    depends_on:
      - seq
      - mssql
      - rabbitmq 
      - identity.api
      - payment.api

  payment.api:
    image: ${ACR_REGISTRY:-edoxa}/payment.api:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Payment.Api/Dockerfile
    depends_on:
      - seq
      - mssql
      - rabbitmq 
      - identity.api

  arena.challenges.api:
    image: ${ACR_REGISTRY:-edoxa}/arena.challenges.api:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Arena.Challenges.Api/Dockerfile
    depends_on:
      - seq
      - mssql
      - rabbitmq 
      - identity.api

  web.gateway:
    image: ${ACR_REGISTRY:-edoxa}/web.gateway:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Web.Gateway/Dockerfile
    depends_on:
      - seq
      - mssql
      - rabbitmq 
      - identity.api
      - cashier.api
      - arena.challenges.api

  web.spa:
    image: ${ACR_REGISTRY:-edoxa}/web.spa:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Web.Spa/Dockerfile
    depends_on:
      - seq

  web.status:
    image: ${ACR_REGISTRY:-edoxa}/web.status:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Web.Status/Dockerfile
    depends_on:
      - seq