version: '3.4'

services:
  mssql.test:
    image: microsoft/mssql-server-linux:latest

  redis.test:
    image: redis:latest

  rabbitmq.test:
    image: rabbitmq:latest

  seedwork.tests:
    image: ${ACR_REGISTRY:-edoxa}/seedwork.tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: test/eDoxa.Seedwork.Tests/Dockerfile
    entrypoint: dotnet test --logger:trx;LogFileName=/var/tmp/eDoxa.Seedwork.TestResults.trx
    volumes:
      - /opt/vsts/test/results:/var/tmp

  idsrv.tests:
    image: ${ACR_REGISTRY:-edoxa}/idsrv.tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: test/eDoxa.IdentityServer.Tests/Dockerfile
    entrypoint: dotnet test --logger:trx;LogFileName=/var/tmp/eDoxa.IdentityServer.TestResults.trx
    volumes:
      - /opt/vsts/test/results:/var/tmp

  idsrv.integration-tests:
    image: ${ACR_REGISTRY:-edoxa}/idsrv.integration-tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: test/eDoxa.IdentityServer.IntegrationTests/Dockerfile
    entrypoint: dotnet test --logger:trx;LogFileName=/var/tmp/eDoxa.IdentityServer.IntegrationTestResults.trx
    volumes:
      - /opt/vsts/test/results:/var/tmp
    depends_on:
      - mssql.test
      - redis.test
      - rabbitmq.test

  identity.tests:
    image: ${ACR_REGISTRY:-edoxa}/identity.tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: test/eDoxa.Identity.Tests/Dockerfile
    entrypoint: dotnet test --logger:trx;LogFileName=/var/tmp/eDoxa.Identity.TestResults.trx
    volumes:
      - /opt/vsts/test/results:/var/tmp

  identity.integration-tests:
    image: ${ACR_REGISTRY:-edoxa}/identity.integration-tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: test/eDoxa.Identity.IntegrationTests/Dockerfile
    entrypoint: dotnet test --logger:trx;LogFileName=/var/tmp/eDoxa.Identity.IntegrationTestResults.trx
    volumes:
      - /opt/vsts/test/results:/var/tmp
    depends_on:
      - mssql.test
      - redis.test
      - rabbitmq.test

  cashier.tests:
    image: ${ACR_REGISTRY:-edoxa}/cashier.tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: test/eDoxa.Cashier.Tests/Dockerfile
    entrypoint: dotnet test --logger:trx;LogFileName=/var/tmp/eDoxa.Cashier.TestResults.trx
    volumes:
      - /opt/vsts/test/results:/var/tmp

  cashier.integration-tests:
    image: ${ACR_REGISTRY:-edoxa}/cashier.integration-tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: test/eDoxa.Cashier.IntegrationTests/Dockerfile
    entrypoint: dotnet test --logger:trx;LogFileName=/var/tmp/eDoxa.Cashier.IntegrationTestResults.trx
    volumes:
      - /opt/vsts/test/results:/var/tmp
    depends_on:
      - mssql.test
      - redis.test
      - rabbitmq.test

  stripe.tests:
    image: ${ACR_REGISTRY:-edoxa}/stripe.tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: test/eDoxa.Stripe.Tests/Dockerfile
    entrypoint: dotnet test --logger:trx;LogFileName=/var/tmp/eDoxa.Stripe.TestResults.trx
    volumes:
      - /opt/vsts/test/results:/var/tmp

  arena.tests:
    image: ${ACR_REGISTRY:-edoxa}/arena.tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: test/eDoxa.Arena.Tests/Dockerfile
    entrypoint: dotnet test --logger:trx;LogFileName=/var/tmp/eDoxa.Arena.TestResults.trx
    volumes:
      - /opt/vsts/test/results:/var/tmp

  arena.challenges.tests:
    image: ${ACR_REGISTRY:-edoxa}/arena.challenges.tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: test/eDoxa.Arena.Challenges.Tests/Dockerfile
    entrypoint: dotnet test --logger:trx;LogFileName=/var/tmp/eDoxa.Arena.Challenges.TestResults.trx
    volumes:
      - /opt/vsts/test/results:/var/tmp

  arena.challenges.integration-tests:
    image: ${ACR_REGISTRY:-edoxa}/arena.challenges.integration-tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: test/eDoxa.Arena.Challenges.IntegrationTests/Dockerfile
    entrypoint: dotnet test --logger:trx;LogFileName=/var/tmp/eDoxa.Arena.Challenges.IntegrationTestResults.trx
    volumes:
      - /opt/vsts/test/results:/var/tmp
    depends_on:
      - mssql.test
      - redis.test
      - rabbitmq.test