version: '3.7'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-CU14-ubuntu

  redis:
    image: redis:5.0.5

  rabbitmq:
    image: rabbitmq:3-management-alpine

  seq:
    image: datalust/seq:latest

  identity.api:
    image: ${ACR_REGISTRY:-edoxa}/dev/identity.api:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Identity.Api/Dockerfile
    depends_on:
      - seq
      - mssql
      - redis

  cashier.api:
    image: ${ACR_REGISTRY:-edoxa}/dev/cashier.api:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Cashier.Api/Dockerfile
    depends_on:
      - seq
      - mssql
      - identity.api
      - payment.api

  payment.api:
    image: ${ACR_REGISTRY:-edoxa}/dev/payment.api:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Payment.Api/Dockerfile
    depends_on:
      - seq
      - mssql
      - identity.api

  notifications.api:
    image: ${ACR_REGISTRY:-edoxa}/dev/notifications.api:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Notifications.Api/Dockerfile
    depends_on:
      - seq      
      - mssql
      - redis
      - identity.api

  games.api:
    image: ${ACR_REGISTRY:-edoxa}/dev/games.api:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Games.Api/Dockerfile
    depends_on:
      - seq
      - mssql
      - redis
      - identity.api

  clans.api:
    image: ${ACR_REGISTRY:-edoxa}/dev/clans.api:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Clans.Api/Dockerfile
    depends_on:
      - seq
      - mssql
      - redis
      - identity.api

  challenges.api:
    image: ${ACR_REGISTRY:-edoxa}/dev/challenges.api:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Challenges.Api/Dockerfile
    depends_on:
      - seq   
      - mssql
      - redis
      - identity.api
      - cashier.api
      - games.api

  challenges.web.aggregator:
    image: ${ACR_REGISTRY:-edoxa}/dev/challenges.web.aggregator:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Challenges.Web.Aggregator/Dockerfile
    depends_on:
      - seq   
      - identity.api
      - cashier.api
      - payment.api
      - notifications.api
      - games.api
      - challenges.api
      - clans.api

  challenges.web.jobs:
    image: ${ACR_REGISTRY:-edoxa}/dev/challenges.web.jobs:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Challenges.Web.Jobs/Dockerfile
    depends_on:
      - seq
      - challenges.api

  challenges.web.gateway:
    image: ${ACR_REGISTRY:-edoxa}/dev/challenges.web.gateway:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Gateway/Dockerfile
    depends_on:
      - seq
      - identity.api
      - cashier.api
      - payment.api
      - notifications.api
      - games.api
      - challenges.api
      - clans.api

  web.spa.proxy:
    image: ${ACR_REGISTRY:-edoxa}/dev/web.spa.proxy:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Web.Spa/Dockerfile
    depends_on:
      - seq
      - redis
      - identity.api
      - challenges.web.gateway
      - web.spa.client

  web.spa.client:
    image: ${ACR_REGISTRY:-edoxa}/dev/web.spa.client:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Web.Spa/ClientApp/Dockerfile

  web.status:
    image: ${ACR_REGISTRY:-edoxa}/dev/web.status:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Web.Status/Dockerfile
    depends_on:
      - seq