version: '3.7'

services:
  mssql.test:
    image: mcr.microsoft.com/mssql/server:2017-CU14-ubuntu

  redis.test:
    image: redis:5.0.5

  seedwork.unit-tests:
    image: ${ACR_REGISTRY:-edoxa}/seedwork.unit-tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: test/eDoxa.Seedwork.UnitTests/Dockerfile

  identity.unit-tests:
    image: ${ACR_REGISTRY:-edoxa}/identity.unit-tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Identity.Api/Dockerfile
      target: unit-tests
      
  identity.integration-tests:
    image: ${ACR_REGISTRY:-edoxa}/identity.integration-tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Identity.Api/Dockerfile
      target: integration-tests
    depends_on:
      - mssql.test
      - redis.test

  payment.unit-tests:
    image: ${ACR_REGISTRY:-edoxa}/payment.unit-tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Payment.Api/Dockerfile
      target: unit-tests

  payment.integration-tests:
    image: ${ACR_REGISTRY:-edoxa}/payment.integration-tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Payment.Api/Dockerfile
      target: integration-tests
    depends_on:
      - mssql.test
      - redis.test

  cashier.unit-tests:
    image: ${ACR_REGISTRY:-edoxa}/cashier.unit-tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Cashier.Api/Dockerfile
      target: unit-tests

  cashier.integration-tests:
    image: ${ACR_REGISTRY:-edoxa}/cashier.integration-tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Cashier.Api/Dockerfile
      target: integration-tests
    depends_on:
      - mssql.test
      - redis.test

  notifications.unit-tests:
    image: ${ACR_REGISTRY:-edoxa}/notifications.unit-tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Notifications.Api/Dockerfile
      target: unit-tests

  notifications.integration-tests:
    image: ${ACR_REGISTRY:-edoxa}/notifications.integration-tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Notifications.Api/Dockerfile
      target: integration-tests
    depends_on:
      - mssql.test
      - redis.test
      
  arena.challenges.unit-tests:
    image: ${ACR_REGISTRY:-edoxa}/arena.challenges.unit-tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Arena.Challenges.Api/Dockerfile
      target: unit-tests

  arena.challenges.integration-tests:
    image: ${ACR_REGISTRY:-edoxa}/arena.challenges.integration-tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Arena.Challenges.Api/Dockerfile
      target: integration-tests
    depends_on:
      - mssql.test
      - redis.test

  arena.games.leagueoflegends.unit-tests:
    image: ${ACR_REGISTRY:-edoxa}/arena.games.leagueoflegends.unit-tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Arena.Games.LeagueOfLegends.Api/Dockerfile
      target: unit-tests

  arena.games.leagueoflegends.integration-tests:
    image: ${ACR_REGISTRY:-edoxa}/arena.games.leagueoflegends.integration-tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Arena.Games.LeagueOfLegends.Api/Dockerfile
      target: integration-tests
    depends_on:
      - mssql.test
      - redis.test  

  organizations.clans.unit-tests:
    image: ${ACR_REGISTRY:-edoxa}/organizations.clans.unit-tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Organizations.Clans.Api/Dockerfile
      target: unit-tests

  organizations.clans.integration-tests:
    image: ${ACR_REGISTRY:-edoxa}/organizations.clans.integration-tests:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Organizations.Clans.Api/Dockerfile
      target: integration-tests
    depends_on:
      - mssql.test
      - redis.test