version: '3.4'

services:
  mssql:
    image: microsoft/mssql-server-linux:latest

  redis:
    image: redis:latest

  rabbitmq:
    image: rabbitmq:latest

  idsrv:
    image: ${ACR_REGISTRY:-edoxa}/idsrv:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.IdentityServer/Dockerfile
    depends_on:
      - mssql
      - redis
      - rabbitmq

  identity.api:
    image: ${ACR_REGISTRY:-edoxa}/identity.api:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Identity.Api/Dockerfile
    depends_on:
      - mssql
      - rabbitmq
      - idsrv

  cashier.api:
    image: ${ACR_REGISTRY:-edoxa}/cashier.api:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Cashier.Api/Dockerfile
    depends_on:
      - mssql
      - rabbitmq 
      - idsrv

  arena.challenges.api:
    image: ${ACR_REGISTRY:-edoxa}/arena.challenges.api:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Arena.Challenges.Api/Dockerfile
    depends_on:
      - mssql
      - rabbitmq 
      - idsrv

  #web.spa:
  #  image: ${ACR_REGISTRY:-edoxa}/web.spa:${ACR_TAG:-latest}
  #  build:
  #    context: .
  #    dockerfile: src/eDoxa.Web.Spa/Dockerfile

  web.status:
    image: ${ACR_REGISTRY:-edoxa}/web.status:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Web.Status/Dockerfile