version: '3.7'

services:
  web-spa:
    image: ${ACR_REGISTRY:-edoxa}/web-spa:${ACR_TAG:-latest}
    build:
      context: .
      dockerfile: src/eDoxa.Web.Spa/Dockerfile.Production
    depends_on:
      - seq
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - REACT_APP_AUTHORITY=http://${HOST:-localhost}:5000
      - REACT_APP_CASHIER_WEB_GATEWAY_URL=http://${HOST:-localhost}:5202
      - REACT_APP_CHALLENGES_WEB_GATEWAY_URL=http://${HOST:-localhost}:5203
      - REACT_APP_WEB_SPA=http://${HOST:-localhost}:5300
      - REACT_APP_BETA_ALERT_DISPLAYED=true
      - REACT_APP_DEPOSIT_BUTTON_DISABLED=false
      - REACT_APP_WITHDRAW_BUTTON_DISABLED=true
      - REACT_APP_BUY_BUTTON_DISABLED=true
      - REACT_APP_FACEBOOK_MCC_ENABLED=true
      - REACT_APP_FACEBOOK_URL=https://www.facebook.com/edoxa.gg/
      - REACT_APP_TWITTER_URL=https://twitter.com/edoxa_gg
      - REACT_APP_DISCORD_URL=https://discord.gg/SvBUH5Y
      - REACT_APP_LINKEDIN_URL=https://www.linkedin.com/company/edoxa
      - REACT_APP_INSTAGRAM_URL=https://www.instagram.com/edoxagg/
      - ConnectionStrings__Redis=${REDIS_CONNECTIONSTRING}
      - ConnectionStrings__AzureKeyVault=${AKV_CONNECTIONSTRING}
      - Authority=http://${HOST:-localhost}:5000
      - Endpoints__IdentityUrl=http://identity-api
      - Serilog__Sink__Seq=http://seq
    ports:
      - "5300:80"