version: '3.7'

services:
  mssql:
    environment:
      - SA_PASSWORD=fnU3Www9TnBDp3MA
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"

  redis:
    ports:
      - "6379:6379"

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5400:80"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AzureKeyVault=${AKV_CONNECTIONSTRING}
      - ConnectionStrings__Redis=${REDIS_CONNECTIONSTRING}
      - ConnectionStrings__SqlServer=${IDENTITY_SQLSERVER_CONNECTIONSTRING}
      - Authority=http://${HOST:-localhost}:5000
      - WebSpaUrl=http://${HOST:-localhost}:5300
      - Endpoints__IdentityUrl=http://identity-api
      - Serilog__Sink__Seq=http://seq
      - Swagger__Endpoints__IdentityUrl=http://${HOST:-localhost}:5000
      - Swagger__Endpoints__PaymentUrl=http://${HOST:-localhost}:5001
      - Swagger__Endpoints__CashierUrl=http://${HOST:-localhost}:5002 
      - Swagger__Endpoints__NotificationsUrl=http://${HOST:-localhost}:5011
      - Swagger__Endpoints__ChallengesUrl=http://${HOST:-localhost}:5003
      - Swagger__Endpoints__GamesUrl=http://${HOST:-localhost}:5005
      - Swagger__Endpoints__ClansUrl=http://${HOST:-localhost}:5010
      - Swagger__Endpoints__ChallengesWebAggregatorUrl=http://${HOST:-localhost}:5303
      - Swagger__Endpoints__CashierWebAggregatorUrl=http://${HOST:-localhost}:5302
    ports:
      - "5000:80"
      - "9000:81"

  cashier-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AzureKeyVault=${AKV_CONNECTIONSTRING}
      - ConnectionStrings__SqlServer=${CASHIER_SQLSERVER_CONNECTIONSTRING}
      - Authority=http://${HOST:-localhost}:5000
      - Endpoints__IdentityUrl=http://identity-api
      - Serilog__Sink__Seq=http://seq
    ports:
      - "5002:80"
      - "9002:81"

  challenges-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AzureKeyVault=${AKV_CONNECTIONSTRING}
      - ConnectionStrings__SqlServer=${CHALLENGES_SQLSERVER_CONNECTIONSTRING}
      - Authority=http://${HOST:-localhost}:5000
      - Endpoints__IdentityUrl=http://identity-api
      - Serilog__Sink__Seq=http://seq
    ports:
      - "5003:80"
      - "9003:81"

  clans-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AzureKeyVault=${AKV_CONNECTIONSTRING}
      - ConnectionStrings__SqlServer=${CLANS_SQLSERVER_CONNECTIONSTRING}
      - Authority=http://${HOST:-localhost}:5000
      - Endpoints__IdentityUrl=http://identity-api
      - Serilog__Sink__Seq=http://seq
    ports:
      - "5010:80"
      - "9010:81"

  games-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AzureKeyVault=${AKV_CONNECTIONSTRING}
      - ConnectionStrings__Redis=${REDIS_CONNECTIONSTRING}
      - ConnectionStrings__SqlServer=${GAMES_SQLSERVER_CONNECTIONSTRING}    
      - Authority=http://${HOST:-localhost}:5000
      - Endpoints__IdentityUrl=http://identity-api
      - Serilog__Sink__Seq=http://seq
      - LeagueOfLegends__ApiKey=RGAPI-db3e65e3-add3-4d18-a518-291875f72b51
    ports:
      - "5005:80"
      - "9005:81"

  notifications-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AzureKeyVault=${AKV_CONNECTIONSTRING}
      - ConnectionStrings__SqlServer=${NOTIFICATIONS_SQLSERVER_CONNECTIONSTRING}
      - Authority=http://${HOST:-localhost}:5000
      - WebSpaUrl=http://${HOST:-localhost}:5300
      - Endpoints__IdentityUrl=http://identity-api    
      - Serilog__Sink__Seq=http://seq
    ports:
      - "5011:80"
      - "9011:81"

  payment-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AzureKeyVault=${AKV_CONNECTIONSTRING}
      - Authority=http://${HOST:-localhost}:5000
      - Endpoints__IdentityUrl=http://identity-api
      - Serilog__Sink__Seq=http://seq
    ports:
      - "5001:80"
      - "9001:81"

  challenges-workers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=${WORKERS_SQLSERVER_CONNECTIONSTRING}
      - ConnectionStrings__AzureKeyVault=${AKV_CONNECTIONSTRING}
      - ConnectionStrings__Redis=${REDIS_CONNECTIONSTRING}
      - Endpoints__ChallengesUrl=http://challenges-api
      - Endpoints__GamesUrl=http://games-api
      - Serilog__Sink__Seq=http://seq
    ports:
      - "5403:80"

  cashier-web-aggregator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AzureKeyVault=${AKV_CONNECTIONSTRING}
      - Authority=http://${HOST:-localhost}:5000
      - Endpoints__IdentityUrl=http://identity-api
      - Endpoints__CashierUrl=http://cashier-api
      - Endpoints__PaymentUrl=http://payment-api
      - Serilog__Sink__Seq=http://seq
    ports:
      - "5302:80"

  challenges-web-aggregator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AzureKeyVault=${AKV_CONNECTIONSTRING}
      - Authority=http://${HOST:-localhost}:5000
      - Endpoints__IdentityUrl=http://identity-api
      - Endpoints__CashierUrl=http://cashier-api
      - Endpoints__ChallengesUrl=http://challenges-api
      - Endpoints__GamesUrl=http://games-api
      - Serilog__Sink__Seq=http://seq
    ports:
      - "5303:80"

  cashier-web-gateway:
    volumes:
      - ./src/eDoxa.Gateways/Cashier.Web.Gateway/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "5202:10000"
      - "15202:9901"

  challenges-web-gateway:
    volumes:
      - ./src/eDoxa.Gateways/Challenges.Web.Gateway/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "5203:10000"
      - "15203:9901"

  web-status:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HealthChecks__Endpoints__0__Name=Identity API
      - HealthChecks__Endpoints__0__Uri=http://identity-api/health
      - HealthChecks__Endpoints__1__Name=Payment API
      - HealthChecks__Endpoints__1__Uri=http://payment-api/health
      - HealthChecks__Endpoints__2__Name=Cashier API
      - HealthChecks__Endpoints__2__Uri=http://cashier-api/health
      - HealthChecks__Endpoints__3__Name=Cashier Web Aggregator
      - HealthChecks__Endpoints__3__Uri=http://cashier-web-aggregator/health
      - HealthChecks__Endpoints__4__Name=Notifications API
      - HealthChecks__Endpoints__4__Uri=http://notifications-api/health
      - HealthChecks__Endpoints__5__Name=Games API
      - HealthChecks__Endpoints__5__Uri=http://games-api/health
      - HealthChecks__Endpoints__6__Name=Clans API
      - HealthChecks__Endpoints__6__Uri=http://clans-api/health
      - HealthChecks__Endpoints__7__Name=Challenges API
      - HealthChecks__Endpoints__7__Uri=http://challenges-api/health
      - HealthChecks__Endpoints__8__Name=Challenges Web Aggregator
      - HealthChecks__Endpoints__8__Uri=http://challenges-web-aggregator/health
      - HealthChecks__Endpoints__9__Name=Challenges Workers
      - HealthChecks__Endpoints__9__Uri=http://challenges-workers/health
      - HealthChecks__Endpoints__10__Name=Web Spa
      - HealthChecks__Endpoints__10__Uri=http://web-spa/health
      - HealthChecks__EvaluationTimeInSeconds=60
      - HealthChecks__MinimumSecondsBetweenFailureNotifications=300
      - Serilog__Sink__Seq=http://seq
    ports:
      - "5500:80"