version: '3.4'

services:
  edoxa.mssql.data:
    environment:
      - SA_PASSWORD=fnU3Www9TnBDp3MA
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"

  edoxa.redis.data:
    ports:
      - "6379:6379"

  edoxa.rabbitmq.broker:
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=4t8SaVXVMy0rT2kM
    ports:
      - "15672:15672"
      - "5672:5672"

  edoxa.identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Sql=${CONNECTIONSTRINGS_SQLSERVER_IDENTITY:-Server=edoxa.mssql.data;Database=eDoxa.Services.Identity;User Id=sa;Password=fnU3Www9TnBDp3MA}
      - ConnectionStrings__Redis=${REDIS:-edoxa.redis.data}
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureKubernetesService__Enable=${AKS_ENABLE:-false}
      - AzureServiceBus__Enable=${ASB_ENABLE:-false}
      - ServiceBus__HostName=${ASB_HOSTNAME:-edoxa.rabbitmq.broker}
      - ServiceBus__UserName=${ASB_USERNAME:-admin}
      - ServiceBus__Password=${ASB_PASSWORD:-4t8SaVXVMy0rT2kM}
      - ServiceBus__RetryCount=${ASB_RETRYCOUNT:-5}
      - ServiceBus__Subscription=Identity
      - Authority=${DOCKER_URL:-http://localhost}:5000
      - Identity__Url=${DOCKER_URL:-http://localhost}:5000
      - Cashier__Url=${DOCKER_URL:-http://localhost}:5003
      - Challenges__Url=${DOCKER_URL:-http://localhost}:5002      
      - Notifications__Url=${DOCKER_URL:-http://localhost}:5005
      - WebSpa__Url=${DOCKER_URL:-http://localhost}:5300
    ports:
      - "5000:80"

  edoxa.challenges.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Sql=${CONNECTIONSTRINGS_SQLSERVER_CHALLENGES:-Server=edoxa.mssql.data;Database=eDoxa.Services.Challenges;User Id=sa;Password=fnU3Www9TnBDp3MA}      
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureServiceBus__Enable=${ASB_ENABLE:-false}
      - ServiceBus__HostName=${ASB_HOSTNAME:-edoxa.rabbitmq.broker}
      - ServiceBus__UserName=${ASB_USERNAME:-admin}
      - ServiceBus__Password=${ASB_PASSWORD:-4t8SaVXVMy0rT2kM}
      - ServiceBus__RetryCount=${ASB_RETRYCOUNT:-5}
      - ServiceBus__Subscription=Challenges      
      - Authority=${DOCKER_URL:-http://localhost}:5000
      - IdentityServer__Url=http://edoxa.identity
    ports:
      - "5002:80"

  edoxa.cashier.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Sql=${CONNECTIONSTRINGS_SQLSERVER_CASHIER:-Server=edoxa.mssql.data;Database=eDoxa.Services.Cashier;User Id=sa;Password=fnU3Www9TnBDp3MA}
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}      
      - AzureServiceBus__Enable=${ASB_ENABLE:-false}
      - ServiceBus__HostName=${ASB_HOSTNAME:-edoxa.rabbitmq.broker}
      - ServiceBus__UserName=${ASB_USERNAME:-admin}
      - ServiceBus__Password=${ASB_PASSWORD:-4t8SaVXVMy0rT2kM}
      - ServiceBus__RetryCount=${ASB_RETRYCOUNT:-5}
      - ServiceBus__Subscription=Cashier      
      - Authority=${DOCKER_URL:-http://localhost}:5000
      - IdentityServer__Url=http://edoxa.identity
    ports:
      - "5003:80"

  edoxa.notifications.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Sql=${CONNECTIONSTRINGS_SQLSERVER_NOTIFICATIONS:-Server=edoxa.mssql.data;Database=eDoxa.Services.Notifications;User Id=sa;Password=fnU3Www9TnBDp3MA}
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureServiceBus__Enable=${ASB_ENABLE:-false}
      - ServiceBus__HostName=${ASB_HOSTNAME:-edoxa.rabbitmq.broker}
      - ServiceBus__UserName=${ASB_USERNAME:-admin}
      - ServiceBus__Password=${ASB_PASSWORD:-4t8SaVXVMy0rT2kM}
      - ServiceBus__RetryCount=${ASB_RETRYCOUNT:-5}
      - ServiceBus__Subscription=Notifications      
      - Authority=${DOCKER_URL:-http://localhost}:5000
      - IdentityServer__Url=http://edoxa.identity
    ports:
      - "5005:80"

  edoxa.challenges.backgroundtasks:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureServiceBus__Enable=${ASB_ENABLE:-false}
      - ServiceBus__HostName=${ASB_HOSTNAME:-edoxa.rabbitmq.broker}
      - ServiceBus__UserName=${ASB_USERNAME:-admin}
      - ServiceBus__Password=${ASB_PASSWORD:-4t8SaVXVMy0rT2kM}
      - ServiceBus__RetryCount=${ASB_RETRYCOUNT:-5}
      - ServiceBus__Subscription=BackgroundTasks
    ports:
      - "5052:80"

  #edoxa.web.spa:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=http://+:80
  #    - ConnectionStrings__Redis=${REDIS:-edoxa.redis.data}
  #    - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
  #    - AzureKubernetesService__Enable=${AKS_ENABLE:-false}
  #    - Authority=${DOCKER_URL:-http://localhost}:5000  
  #    - Identity__Url=${DOCKER_URL:-http://localhost}:5000
  #    - Cashier__Url=${DOCKER_URL:-http://localhost}:5003
  #    - Challenges__Url=${DOCKER_URL:-http://localhost}:5002
  #    - Notifications__Url=${DOCKER_URL:-http://localhost}:5005
  #    - WebSpa__Url=${DOCKER_URL:-http://localhost}:5300
  #  ports:
  #    - "5300:80"

  edoxa.web.status:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}            
      - HealthChecks__Endpoints__0__Name=eDoxa Web Spa
      - HealthChecks__Endpoints__0__Uri=http://edoxa.web.spa/health
      - HealthChecks__Endpoints__1__Name=eDoxa Identity
      - HealthChecks__Endpoints__1__Uri=http://edoxa.identity/health
      - HealthChecks__Endpoints__2__Name=eDoxa Cashier API
      - HealthChecks__Endpoints__2__Uri=http://edoxa.cashier.api/health
      - HealthChecks__Endpoints__3__Name=eDoxa Notifications API
      - HealthChecks__Endpoints__3__Uri=http://edoxa.notifications.api/health
      - HealthChecks__Endpoints__4__Name=eDoxa Challenges API
      - HealthChecks__Endpoints__4__Uri=http://edoxa.challenges.api/health
      - HealthChecks__Endpoints__5__Name=eDoxa Challenges Background Tasks
      - HealthChecks__Endpoints__5__Uri=http://edoxa.challenges.backgroundtasks/health
      - HealthChecks__EvaluationTimeInSeconds=15
      - HealthChecks__MinimumSecondsBetweenFailureNotifications=60
    ports:
      - "5500:80"