version: '3.7'

services:
  mssql:
    environment:
      - SA_PASSWORD=fnU3Www9TnBDp3MA
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"

  redis:
    ports:
      - "6379:6379"

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5400:80"

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - APPINSIGHTS_INSTRUMENTATIONKEY=47ce723c-52e7-4714-931a-19e72c037c9a
      - ConnectionStrings__SqlServer=${MSSQL_IDENTITY:-Server=mssql;Database=Services.Identity;User Id=sa;Password=fnU3Www9TnBDp3MA}
      - ConnectionStrings__Redis=${REDIS:-redis}
      - ConnectionStrings__AzureServiceBus=${ASB_HOSTNAME}
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - AzureKubernetesServiceEnabled=${AKS_ENABLE:-false}
      - Authority__PrivateUrl=http://identity.api
      - Authority__PublicUrl=http://${HOST:-localhost}:5000
      - IdentityServer__IdentityUrl=http://${HOST:-localhost}:5000
      - IdentityServer__PaymentUrl=http://${HOST:-localhost}:5001
      - IdentityServer__CashierUrl=http://${HOST:-localhost}:5002 
      - IdentityServer__NotificationsUrl=http://${HOST:-localhost}:5011
      - IdentityServer__ArenaChallengesUrl=http://${HOST:-localhost}:5003
      - IdentityServer__ArenaGamesUrl=http://${HOST:-localhost}:5005
      - IdentityServer__ArenaGamesLeagueOfLegendsUrl=http://${HOST:-localhost}:5006
      - IdentityServer__OrganizationsClansUrl=http://${HOST:-localhost}:5010
      - IdentityServer__Web__SpaUrl=http://${HOST:-localhost}:5300
    ports:
      - "5000:80"

  payment.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - APPINSIGHTS_INSTRUMENTATIONKEY=47ce723c-52e7-4714-931a-19e72c037c9a
      - ConnectionStrings__SqlServer=${MSSQL_PAYMENT:-Server=mssql;Database=Services.Payment;User Id=sa;Password=fnU3Www9TnBDp3MA}
      - ConnectionStrings__AzureServiceBus=${ASB_HOSTNAME}
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}      
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - Authority__PrivateUrl=http://identity.api
      - Authority__PublicUrl=http://${HOST:-localhost}:5000
    ports:
      - "5001:80"

  cashier.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - APPINSIGHTS_INSTRUMENTATIONKEY=47ce723c-52e7-4714-931a-19e72c037c9a
      - ConnectionStrings__SqlServer=${MSSQL_CASHIER:-Server=mssql;Database=Services.Cashier;User Id=sa;Password=fnU3Www9TnBDp3MA}
      - ConnectionStrings__AzureServiceBus=${ASB_HOSTNAME} 
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}      
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - HealthChecks__PaymentUrl=http://payment.api/health
      - Authority__PrivateUrl=http://identity.api
      - Authority__PublicUrl=http://${HOST:-localhost}:5000      
    ports:
      - "5002:80"

  notifications.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - APPINSIGHTS_INSTRUMENTATIONKEY=47ce723c-52e7-4714-931a-19e72c037c9a
      - ConnectionStrings__SqlServer=${MSSQL_NOTIFICATIONS:-Server=mssql;Database=Services.Notifications;User Id=sa;Password=fnU3Www9TnBDp3MA}
      - ConnectionStrings__Redis=${REDIS:-redis}
      - ConnectionStrings__AzureServiceBus=${ASB_HOSTNAME}
      - ConnectionStrings__AzureStorage=${AS_NOTIFICATIONS:-DefaultEndpointsProtocol=https;AccountName=edoxa;AccountKey=KjL1k5kHKwVPRPGMSCbvI4w9kx/ql11p+P86u3XnsohS6kGTS2E8f/sqxnEEykJ5lblC3LrHo1KmujXs5cGN/Q==;EndpointSuffix=core.windows.net;BlobEndpoint=https://edoxa.blob.core.windows.net/dev/}
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - Authority__PrivateUrl=http://identity.api
      - Authority__PublicUrl=http://${HOST:-localhost}:5000      
    ports:
      - "5011:80"

  arena.challenges.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - APPINSIGHTS_INSTRUMENTATIONKEY=47ce723c-52e7-4714-931a-19e72c037c9a
      - ConnectionStrings__SqlServer=${MSSQL_ARENA_CHALLENGES:-Server=mssql;Database=Services.Arena.Challenges;User Id=sa;Password=fnU3Www9TnBDp3MA}      
      - ConnectionStrings__Redis=${REDIS:-redis}
      - ConnectionStrings__AzureServiceBus=${ASB_HOSTNAME}
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - Authority__PrivateUrl=http://identity.api
      - Authority__PublicUrl=http://${HOST:-localhost}:5000      
    ports:
      - "5003:80"

  arena.games.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - APPINSIGHTS_INSTRUMENTATIONKEY=47ce723c-52e7-4714-931a-19e72c037c9a
      - ConnectionStrings__SqlServer=${MSSQL_ARENA_GAMES:-Server=mssql;Database=Services.Arena.Games;User Id=sa;Password=fnU3Www9TnBDp3MA}      
      - ConnectionStrings__AzureServiceBus=${ASB_HOSTNAME}
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - Authority__PrivateUrl=http://identity.api
      - Authority__PublicUrl=http://${HOST:-localhost}:5000      
    ports:
      - "5005:80"

  arena.games.leagueoflegends.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - APPINSIGHTS_INSTRUMENTATIONKEY=47ce723c-52e7-4714-931a-19e72c037c9a
      - ConnectionStrings__Redis=${REDIS:-redis}
      - ConnectionStrings__AzureServiceBus=${ASB_HOSTNAME}
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - Authority__PrivateUrl=http://identity.api
      - Authority__PublicUrl=http://${HOST:-localhost}:5000      
    ports:
      - "5006:80"

  organizations.clans.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - APPINSIGHTS_INSTRUMENTATIONKEY=47ce723c-52e7-4714-931a-19e72c037c9a
      - ConnectionStrings__SqlServer=${MSSQL_ORGANIZATIONS_CLANS:-Server=mssql;Database=Services.Organizations.Clans;User Id=sa;Password=fnU3Www9TnBDp3MA}
      - ConnectionStrings__AzureServiceBus=${ASB_HOSTNAME}
      - ConnectionStrings__AzureStorage=${AS_ORGANIZATIONS_CLANS:-DefaultEndpointsProtocol=https;AccountName=edoxa;AccountKey=KjL1k5kHKwVPRPGMSCbvI4w9kx/ql11p+P86u3XnsohS6kGTS2E8f/sqxnEEykJ5lblC3LrHo1KmujXs5cGN/Q==;EndpointSuffix=core.windows.net;BlobEndpoint=https://edoxa.blob.core.windows.net/dev/}
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - Authority__PrivateUrl=http://identity.api
      - Authority__PublicUrl=http://${HOST:-localhost}:5000      
    ports:
      - "5010:80"

  web.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - APPINSIGHTS_INSTRUMENTATIONKEY=47ce723c-52e7-4714-931a-19e72c037c9a
      - HealthChecks__IdentityUrl=http://identity.api/health
      - HealthChecks__CashierUrl=http://cashier.api/health
      - HealthChecks__PaymentUrl=http://payment.api/health
      - HealthChecks__NotificationsUrl=http://notifications.api/health
      - HealthChecks__ArenaChallengesUrl=http://arena.challenges.api/health
      - HealthChecks__ArenaGamesUrl=http://arena.games.api/health
      - HealthChecks__ArenaGamesLeagueOfLegendsUrl=http://arena.games.leagueoflegends.api/health
      - HealthChecks__OrganizationsClansUrl=http://organizations.clans.api/health
      - Authority__PrivateUrl=http://identity.api
      - Authority__PublicUrl=http://${HOST:-localhost}:5000
    ports:
      - "5200:80"
    volumes:
      - ./src/eDoxa.Web.Gateway:/app

  web.spa.proxy:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - APPINSIGHTS_INSTRUMENTATIONKEY=47ce723c-52e7-4714-931a-19e72c037c9a
      - ConnectionStrings__Redis=${REDIS:-redis}
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - AzureKubernetesServiceEnabled=${AKS_ENABLE:-false}
      - Authority__PublicUrl=http://${HOST:-localhost}:5000
      - Authority__PrivateUrl=http://identity.api
      - Web__GatewayUrl=http://${HOST:-localhost}:5200
      - Web__ClientUrl=http://${HOST:-localhost}:3000
      - HealthChecks__Web__GatewayUrl=http://web.gateway/health
    ports:
      - "5300:80"

  web.spa.client:
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_AUTHORITY=http://${HOST:-localhost}:5000
      - REACT_APP_REDIRECT_URI=http://${HOST:-localhost}:5300/callback
      - REACT_APP_CLIENT_ID=edoxa.web.spa
      - REACT_APP_RESPONSE_TYPE=token id_token
      - REACT_APP_SCOPE=openid profile country roles permissions games identity.api payment.api cashier.api arena.challenges.api arena.games.api arena.games.leagueoflegends.api organizations.clans.api
      - REACT_APP_WEB_GATEWAY=http://${HOST:-localhost}:5200
      - REACT_APP_SILENT_REFRESH_URI=http://${HOST:-localhost}:5300/silent-refresh
      - REACT_APP_STRIPE_APIKEYS_PUBLISHABLEKEY=pk_test_2iUjQQxve1uP7BJOxs5SwQvj
    volumes:
      - './src/eDoxa.Web.Spa/ClientApp:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'

  web.status:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - APPINSIGHTS_INSTRUMENTATIONKEY=47ce723c-52e7-4714-931a-19e72c037c9a
      - HealthChecks__Endpoints__0__Name=eDoxa Identity API
      - HealthChecks__Endpoints__0__Uri=http://identity.api/health
      - HealthChecks__Endpoints__1__Name=eDoxa Payment API
      - HealthChecks__Endpoints__1__Uri=http://payment.api/health
      - HealthChecks__Endpoints__2__Name=eDoxa Cashier API
      - HealthChecks__Endpoints__2__Uri=http://cashier.api/health
      - HealthChecks__Endpoints__3__Name=eDoxa Notifications API
      - HealthChecks__Endpoints__3__Uri=http://notifications.api/health
      - HealthChecks__Endpoints__4__Name=eDoxa Arena Challenges API
      - HealthChecks__Endpoints__4__Uri=http://arena.challenges.api/health
      - HealthChecks__Endpoints__5__Name=eDoxa Arena Games API
      - HealthChecks__Endpoints__5__Uri=http://arena.games.api/health
      - HealthChecks__Endpoints__6__Name=eDoxa Arena Games LeagueOfLegends API
      - HealthChecks__Endpoints__6__Uri=http://arena.games.leagueoflegends.api/health
      - HealthChecks__Endpoints__7__Name=eDoxa Organizations Clans API
      - HealthChecks__Endpoints__7__Uri=http://organizations.clans.api/health
      - HealthChecks__Endpoints__8__Name=eDoxa Web Gateway
      - HealthChecks__Endpoints__8__Uri=http://web.gateway/health
      - HealthChecks__Endpoints__9__Name=eDoxa Web Spa
      - HealthChecks__Endpoints__9__Uri=http://web.spa.proxy/health
      - HealthChecks__EvaluationTimeInSeconds=60
      - HealthChecks__MinimumSecondsBetweenFailureNotifications=300
    ports:
      - "5500:80"