version: '3.7'

services:
  mssql.test:
    environment:
      - SA_PASSWORD=fnU3Www9TnBDp3MA
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "5433:1433"

  redis.test:
    ports:
      - "10379:6379"

  rabbitmq.test:
    ports:
      - "19672:15672"
      - "9672:5672"

  seedwork.unit-tests:
    entrypoint: dotnet test -c Release --logger:trx;LogFileName=/var/tmp/eDoxa.Seedwork.UnitTests.trx
    volumes:
      - ${BUILD_ARTIFACTDIRECTORY:-.}/vsts/test/results:/var/tmp

  identity.unit-tests:
    entrypoint: dotnet test -c Release --logger:trx;LogFileName=/var/tmp/eDoxa.Identity.UnitTests.trx
    volumes:
      - ${BUILD_ARTIFACTDIRECTORY:-.}/vsts/test/results:/var/tmp

  identity.integration-tests:
    entrypoint: dotnet test -c Release --logger:trx;LogFileName=/var/tmp/eDoxa.Identity.IntegrationTests.trx
    environment:
      - ASPNETCORE_ENVIRONMENT=Testing
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__SqlServer=${MSSQL_IDENTITY:-Server=mssql.test;Database=Services.Identity.IntegrationTests;User Id=sa;Password=fnU3Www9TnBDp3MA}
      - ConnectionStrings__Redis=${REDIS:-redis.test}
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - AzureServiceBusEnabled=${ASB_ENABLE:-false}
      - ServiceBus__HostName=${ASB_HOSTNAME:-rabbitmq.test}      
      - ServiceBus__SubscriptionName=identity
      - AzureKubernetesServiceEnabled=${AKS_ENABLE:-false}
      - Authority__PrivateUrl=${URL:-http://localhost}:5000
      - Authority__PublicUrl=${URL:-http://localhost}:5000
      - IdentityServer__IdentityUrl=${URL:-http://localhost}:5000
      - IdentityServer__CashierUrl=${URL:-http://localhost}:5002
      - IdentityServer__ArenaChallengesUrl=${URL:-http://localhost}:5003
      - IdentityServer__Web__SpaUrl=${URL:-http://localhost}:5300
      - SwaggerEnabled=${SwaggerEnabled:-false}
    volumes:
      - ${BUILD_ARTIFACTDIRECTORY:-.}/vsts/test/results:/var/tmp

  payment.unit-tests:
    entrypoint: dotnet test -c Release --logger:trx;LogFileName=/var/tmp/eDoxa.Payment.UnitTests.trx
    volumes:
      - ${BUILD_ARTIFACTDIRECTORY:-.}/vsts/test/results:/var/tmp

  cashier.unit-tests:
    entrypoint: dotnet test -c Release --logger:trx;LogFileName=/var/tmp/eDoxa.Cashier.UnitTests.trx
    volumes:
      - ${BUILD_ARTIFACTDIRECTORY:-.}/vsts/test/results:/var/tmp

  cashier.integration-tests:
    entrypoint: dotnet test -c Release --logger:trx;LogFileName=/var/tmp/eDoxa.Cashier.IntegrationTests.trx
    environment:
      - ASPNETCORE_ENVIRONMENT=Testing
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__SqlServer=${MSSQL_CASHIER:-Server=mssql.test;Database=Services.Cashier.IntegrationTests;User Id=sa;Password=fnU3Www9TnBDp3MA}
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}      
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - AzureServiceBusEnabled=${ASB_ENABLE:-false}
      - ServiceBus__HostName=${ASB_HOSTNAME:-rabbitmq.test}      
      - ServiceBus__SubscriptionName=cashier
      - HealthChecks__PaymentUrl=${URL:-http://localhost}:5002/health
      - Authority__PrivateUrl=${URL:-http://localhost}:5000
      - Authority__PublicUrl=${URL:-http://localhost}:5000
      - SwaggerEnabled=${SwaggerEnabled:-false}
    volumes:
      - ${BUILD_ARTIFACTDIRECTORY:-.}/vsts/test/results:/var/tmp
      
  arena.challenges.unit-tests:
    entrypoint: dotnet test -c Release --logger:trx;LogFileName=/var/tmp/eDoxa.Arena.Challenges.UnitTests.trx
    volumes:
      - ${BUILD_ARTIFACTDIRECTORY:-.}/vsts/test/results:/var/tmp

  arena.challenges.integration-tests:
    entrypoint: dotnet test -c Release --logger:trx;LogFileName=/var/tmp/eDoxa.Arena.Challenges.IntegrationTests.trx
    environment:
      - ASPNETCORE_ENVIRONMENT=Testing
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__SqlServer=${MSSQL_CHALLENGE:-Server=mssql.test;Database=Services.Arena.Challenges.IntegrationTests;User Id=sa;Password=fnU3Www9TnBDp3MA}      
      - ConnectionStrings__Redis=${REDIS:-redis.test}
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - AzureServiceBusEnabled=${ASB_ENABLE:-false}
      - ServiceBus__HostName=${ASB_HOSTNAME:-rabbitmq.test}      
      - ServiceBus__SubscriptionName=arena.challenges
      - Authority__PrivateUrl=${URL:-http://localhost}:5000
      - Authority__PublicUrl=${URL:-http://localhost}:5000
      - SwaggerEnabled=${SwaggerEnabled:-false}
    volumes:
      - ${BUILD_ARTIFACTDIRECTORY:-.}/vsts/test/results:/var/tmp