version: '3.4'

services:
  mssql.test:
    environment:
      - SA_PASSWORD=fnU3Www9TnBDp3MA
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "5433:1433"

  redis.test:
    ports:
      - "6379:6379"

  rabbitmq.test:
    ports:
      - "15672:15672"
      - "5672:5672"

  idsrv.integration-tests:
    environment:
      - ASPNETCORE_ENVIRONMENT=Testing
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__SqlServer=Server=mssql.test;Database=Services.Identity;User Id=sa;Password=fnU3Www9TnBDp3MA
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - AzureServiceBus__Enable=${ASB_ENABLE:-false}
      - ServiceBus__HostName=${ASB_HOSTNAME:-rabbitmq.test}
      - ServiceBus__Subscription=IdentityServer

  identity.integration-tests:
    environment:
      - ASPNETCORE_ENVIRONMENT=Testing
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__SqlServer=Server=mssql.test;Database=Services.Identity;User Id=sa;Password=fnU3Www9TnBDp3MA
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - AzureServiceBus__Enable=${ASB_ENABLE:-false}
      - ServiceBus__HostName=${ASB_HOSTNAME:-rabbitmq.test}
      - ServiceBus__Subscription=Identity

  cashier.integration-tests:
    environment:
      - ASPNETCORE_ENVIRONMENT=Testing
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__SqlServer=Server=mssql.test;Database=Services.Cashier;User Id=sa;Password=fnU3Www9TnBDp3MA
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - AzureServiceBus__Enable=${ASB_ENABLE:-false}
      - ServiceBus__HostName=${ASB_HOSTNAME:-rabbitmq.test}
      - ServiceBus__Subscription=Cashier

  arena.challenges.integration-tests:
    environment:
      - ASPNETCORE_ENVIRONMENT=Testing
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__SqlServer=Server=mssql.test;Database=Services.Arena.Challenges;User Id=sa;Password=fnU3Www9TnBDp3MA
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - AzureServiceBus__Enable=${ASB_ENABLE:-false}
      - ServiceBus__HostName=${ASB_HOSTNAME:-rabbitmq.test}
      - ServiceBus__Subscription=Arena.Challenges