version: '3.7'

services:
  mssql:
    environment:
      - SA_PASSWORD=fnU3Www9TnBDp3MA
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"

  redis:
    ports:
      - "6379:6379"

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5400:80"

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY}
      - ConnectionStrings__SqlServer=${MSSQL_IDENTITY:-Server=mssql;Database=Services.Identity;User Id=sa;Password=fnU3Www9TnBDp3MA}
      - ConnectionStrings__Redis=${REDIS:-redis}
      - ConnectionStrings__AzureServiceBus=${ASB_HOSTNAME}
      - ConnectionStrings__AzureKeyVault=${AKV_CONNECTIONSTRING}
      - AzureKubernetesServiceEnabled=${AKS_ENABLE:-false}
      - Authority=http://${HOST:-localhost}:5000
      - WebSpaProxyUrl=http://${HOST:-localhost}:5300
      - Endpoints__IdentityUrl=http://identity.api
      - Swagger__Enabled=true
      - Swagger__Endpoints__IdentityUrl=http://${HOST:-localhost}:5000
      - Swagger__Endpoints__PaymentUrl=http://${HOST:-localhost}:5001
      - Swagger__Endpoints__CashierUrl=http://${HOST:-localhost}:5002 
      - Swagger__Endpoints__NotificationsUrl=http://${HOST:-localhost}:5011
      - Swagger__Endpoints__ChallengesUrl=http://${HOST:-localhost}:5003
      - Swagger__Endpoints__GamesUrl=http://${HOST:-localhost}:5005
      - Swagger__Endpoints__ClansUrl=http://${HOST:-localhost}:5010
    ports:
      - "5000:80"

  payment.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY}
      - ConnectionStrings__SqlServer=${MSSQL_PAYMENT:-Server=mssql;Database=Services.Payment;User Id=sa;Password=fnU3Www9TnBDp3MA}
      - ConnectionStrings__AzureServiceBus=${ASB_HOSTNAME}
      - ConnectionStrings__AzureKeyVault=${AKV_CONNECTIONSTRING}
      - Authority=http://${HOST:-localhost}:5000
      - Endpoints__IdentityUrl=http://identity.api
    ports:
      - "5001:80"

  cashier.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY}
      - ConnectionStrings__SqlServer=${MSSQL_CASHIER:-Server=mssql;Database=Services.Cashier;User Id=sa;Password=fnU3Www9TnBDp3MA}
      - ConnectionStrings__AzureServiceBus=${ASB_HOSTNAME} 
      - ConnectionStrings__AzureKeyVault=${AKV_CONNECTIONSTRING}
      - Authority=http://${HOST:-localhost}:5000
      - Endpoints__IdentityUrl=http://identity.api
      - Endpoints__PaymentUrl=http://payment.api
    ports:
      - "5002:80"

  notifications.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY}
      - ConnectionStrings__SqlServer=${MSSQL_NOTIFICATIONS:-Server=mssql;Database=Services.Notifications;User Id=sa;Password=fnU3Www9TnBDp3MA}
      - ConnectionStrings__AzureServiceBus=${ASB_HOSTNAME}
      - ConnectionStrings__AzureBlobStorage=${AS_NOTIFICATIONS:-DefaultEndpointsProtocol=https;AccountName=edoxa;AccountKey=KjL1k5kHKwVPRPGMSCbvI4w9kx/ql11p+P86u3XnsohS6kGTS2E8f/sqxnEEykJ5lblC3LrHo1KmujXs5cGN/Q==;EndpointSuffix=core.windows.net;BlobEndpoint=https://edoxa.blob.core.windows.net/dev/}
      - ConnectionStrings__AzureKeyVault=${AKV_CONNECTIONSTRING}
      - Authority=http://${HOST:-localhost}:5000  
      - Endpoints__IdentityUrl=http://identity.api    
    ports:
      - "5011:80"

  arena.challenges.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY}
      - ConnectionStrings__SqlServer=${MSSQL_ARENA_CHALLENGES:-Server=mssql;Database=Services.Arena.Challenges;User Id=sa;Password=fnU3Www9TnBDp3MA}      
      - ConnectionStrings__Redis=${REDIS:-redis}
      - ConnectionStrings__AzureServiceBus=${ASB_HOSTNAME}
      - ConnectionStrings__AzureKeyVault=${AKV_CONNECTIONSTRING}
      - Authority=http://${HOST:-localhost}:5000
      - Endpoints__IdentityUrl=http://identity.api
      - Endpoints__CashierUrl=http://cashier.api
      - Endpoints__GamesUrl=http://arena.games.api
    ports:
      - "5003:80"

  arena.games.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY}
      - ConnectionStrings__SqlServer=${MSSQL_ARENA_GAMES:-Server=mssql;Database=Services.Arena.Games;User Id=sa;Password=fnU3Www9TnBDp3MA}      
      - ConnectionStrings__Redis=${REDIS:-redis}
      - ConnectionStrings__AzureServiceBus=${ASB_HOSTNAME}
      - ConnectionStrings__AzureKeyVault=${AKV_CONNECTIONSTRING}
      - Authority=http://${HOST:-localhost}:5000
      - Endpoints__IdentityUrl=http://identity.api
    ports:
      - "5005:80"

  organizations.clans.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY}
      - ConnectionStrings__SqlServer=${MSSQL_ORGANIZATIONS_CLANS:-Server=mssql;Database=Services.Organizations.Clans;User Id=sa;Password=fnU3Www9TnBDp3MA}
      - ConnectionStrings__AzureServiceBus=${ASB_HOSTNAME}
      - ConnectionStrings__AzureBlobStorage=${AS_ORGANIZATIONS_CLANS:-DefaultEndpointsProtocol=https;AccountName=edoxa;AccountKey=KjL1k5kHKwVPRPGMSCbvI4w9kx/ql11p+P86u3XnsohS6kGTS2E8f/sqxnEEykJ5lblC3LrHo1KmujXs5cGN/Q==;EndpointSuffix=core.windows.net;BlobEndpoint=https://edoxa.blob.core.windows.net/dev/}
      - ConnectionStrings__AzureKeyVault=${AKV_CONNECTIONSTRING}
      - Authority=http://${HOST:-localhost}:5000
      - Endpoints__IdentityUrl=http://identity.api
    ports:
      - "5010:80"

  web.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY}
      - Authority=http://${HOST:-localhost}:5000
      - Endpoints__IdentityUrl=http://identity.api
      - Endpoints__CashierUrl=http://cashier.api
      - Endpoints__PaymentUrl=http://payment.api
      - Endpoints__NotificationsUrl=http://notifications.api
      - Endpoints__ChallengesUrl=http://arena.challenges.api
      - Endpoints__GamesUrl=http://arena.games.api
      - Endpoints__ClansUrl=http://organizations.clans.api
    ports:
      - "5200:80"
    volumes:
      - ./src/eDoxa.Web.Gateway:/app

  web.spa.proxy:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY}
      - ConnectionStrings__Redis=${REDIS:-redis}
      - ConnectionStrings__AzureKeyVault=${AKV_CONNECTIONSTRING}
      - AzureKubernetesServiceEnabled=${AKS_ENABLE:-false}
      - Authority=http://${HOST:-localhost}:5000
      - WebSpaClientUrl=http://${HOST:-localhost}:3000
      - WebGatewayUrl=http://web.gateway
      - Endpoints__IdentityUrl=http://identity.api
    ports:
      - "5300:80"

  web.spa.client:
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_AUTHORITY=http://${HOST:-localhost}:5000
      - REACT_APP_REDIRECT_URI=http://${HOST:-localhost}:5300/callback
      - REACT_APP_CLIENT_ID=edoxa.web.spa
      - REACT_APP_RESPONSE_TYPE=token id_token
      - REACT_APP_SCOPE=openid profile country roles permissions games identity.api payment.api cashier.api arena.challenges.api arena.games.api organizations.clans.api
      - REACT_APP_WEB_GATEWAY=http://${HOST:-localhost}:5200
      - REACT_APP_SILENT_REFRESH_URI=http://${HOST:-localhost}:5300/silent-refresh
      - REACT_APP_STRIPE_APIKEYS_PUBLISHABLEKEY=pk_test_2iUjQQxve1uP7BJOxs5SwQvj
    volumes:
      - './src/eDoxa.Web.Spa/ClientApp:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'

  web.status:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY}
      - HealthChecks__Endpoints__0__Name=eDoxa Identity API
      - HealthChecks__Endpoints__0__Uri=http://identity.api/health
      - HealthChecks__Endpoints__1__Name=eDoxa Payment API
      - HealthChecks__Endpoints__1__Uri=http://payment.api/health
      - HealthChecks__Endpoints__2__Name=eDoxa Cashier API
      - HealthChecks__Endpoints__2__Uri=http://cashier.api/health
      - HealthChecks__Endpoints__3__Name=eDoxa Notifications API
      - HealthChecks__Endpoints__3__Uri=http://notifications.api/health
      - HealthChecks__Endpoints__4__Name=eDoxa Challenges API
      - HealthChecks__Endpoints__4__Uri=http://arena.challenges.api/health
      - HealthChecks__Endpoints__5__Name=eDoxa Games API
      - HealthChecks__Endpoints__5__Uri=http://arena.games.api/health
      - HealthChecks__Endpoints__6__Name=eDoxa Clans API
      - HealthChecks__Endpoints__6__Uri=http://organizations.clans.api/health
      - HealthChecks__Endpoints__7__Name=eDoxa Web Gateway
      - HealthChecks__Endpoints__7__Uri=http://web.gateway/health
      - HealthChecks__Endpoints__8__Name=eDoxa Web Spa
      - HealthChecks__Endpoints__8__Uri=http://web.spa.proxy/health
      - HealthChecks__EvaluationTimeInSeconds=60
      - HealthChecks__MinimumSecondsBetweenFailureNotifications=300
    ports:
      - "5500:80"