version: '3.4'

services:
  mssql.test:
    environment:
      - SA_PASSWORD=fnU3Www9TnBDp3MA
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "5433:1433"

  arena.challenges.integration-tests:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=mssql.test;Database=Services.Arena.Challenges;User Id=sa;Password=fnU3Www9TnBDp3MA
      - AzureKeyVault__Name=${AKV_NAME:-edoxa-dev}
      - AzureKeyVault__ClientId=${AKV_CLIENT_ID:-bb6ade30-85d1-4bb7-a90f-047a5ffe9323}
      - AzureKeyVault__ClientSecret=${AKV_CLIENT_SECRET:-j*y+Do-?iwAQjGTCA1DRyT7UT9wj7NN5}
      - AzureServiceBus__Enable=${ASB_ENABLE:-false}
      - ServiceBus__HostName=${ASB_HOSTNAME:-rabbitmq}
      - ServiceBus__UserName=${ASB_USERNAME:-admin}
      - ServiceBus__Password=${ASB_PASSWORD:-4t8SaVXVMy0rT2kM}
      - ServiceBus__RetryCount=${ASB_RETRYCOUNT:-5}
      - ServiceBus__Subscription=Arena.Challenges
    entrypoint: dotnet test --logger:trx;LogFileName=/var/tmp/eDoxa.Arena.Challenges.IntegrationTestResults.trx    
    volumes:
      - /opt/vsts/test/results:/var/tmp