apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "subchart.configmap.fullname" . }}
  labels:
{{ include "subchart.labels" . | indent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.global.infrastructure.aspnetcore.environment }}
  ASPNETCORE_URLS: {{ .Values.global.infrastructure.aspnetcore.urls }}
  ApplicationInsights__InstrumentationKey: {{ .Values.global.infrastructure.applicationInsights.instrumentationKey }}
  ConnectionStrings__SqlServer: {{ include "mssql" . }}
  ConnectionStrings__Redis: {{ include "redis" . }}
  AzureKeyVault__Name: {{ .Values.global.infrastructure.azureKeyVault.name }}
  AzureKeyVault__ClientId: {{ .Values.global.infrastructure.azureKeyVault.clientId }}
  AzureKeyVault__ClientSecret: {{ .Values.global.infrastructure.azureKeyVault.clientSecret }}
  AzureServiceBusEnabled: {{ .Values.global.infrastructure.azureServiceBus.enabled }}
  ServiceBus__HostName: {{ .Values.global.infrastructure.azureServiceBus.hostName }}
  ServiceBus__SubscriptionName: {{ .Values.serviceBus.subscriptionName }}
  Authority__PrivateUrl: {{ include "url.internal" (dict "ServiceName" .Values.global.app.service.api.identity "Context" .) }}
  Authority__PublicUrl: {{ include "url.external" (dict "IngressPath" .Values.global.infrastructure.ingress.api.identity "Context" .) }}
  Serilog__Sink__Seq: {{ include "seq" . }}