//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDoxa.Cashier.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eDoxa.Cashier.Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CustomerCardsController_BadRequest_CreateCustomerCardAsync {
            get {
                return ResourceManager.GetString("CustomerCardsController_BadRequest_CreateCustomerCardAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CustomerCardsController_BadRequest_DeleteCustomerCardAsync {
            get {
                return ResourceManager.GetString("CustomerCardsController_BadRequest_DeleteCustomerCardAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CustomerCardsController_BadRequest_FetchCustomerCardsAsync {
            get {
                return ResourceManager.GetString("CustomerCardsController_BadRequest_FetchCustomerCardsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CustomerCardsController_BadRequest_FindCustomerCardAsync {
            get {
                return ResourceManager.GetString("CustomerCardsController_BadRequest_FindCustomerCardAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CustomerCardsController_Error_CreateCustomerCardAsync {
            get {
                return ResourceManager.GetString("CustomerCardsController_Error_CreateCustomerCardAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CustomerCardsController_Error_DeleteCustomerCardAsync {
            get {
                return ResourceManager.GetString("CustomerCardsController_Error_DeleteCustomerCardAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CustomerCardsController_Error_FetchCustomerCardsAsync {
            get {
                return ResourceManager.GetString("CustomerCardsController_Error_FetchCustomerCardsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CustomerCardsController_Error_FindCustomerCardAsync {
            get {
                return ResourceManager.GetString("CustomerCardsController_Error_FindCustomerCardAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CustomerCardsController_Ok_DeleteCustomerCardAsync {
            get {
                return ResourceManager.GetString("CustomerCardsController_Ok_DeleteCustomerCardAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CustomersController_BadRequest_FindCustomerShippingAddressAsync {
            get {
                return ResourceManager.GetString("CustomersController_BadRequest_FindCustomerShippingAddressAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CustomersController_BadRequest_UpdateCustomerDefaultSourceAsync {
            get {
                return ResourceManager.GetString("CustomersController_BadRequest_UpdateCustomerDefaultSourceAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CustomersController_BadRequest_UpdateCustomerShippingAddressAsync {
            get {
                return ResourceManager.GetString("CustomersController_BadRequest_UpdateCustomerShippingAddressAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CustomersController_Error_FindCustomerShippingAddressAsync {
            get {
                return ResourceManager.GetString("CustomersController_Error_FindCustomerShippingAddressAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CustomersController_Error_UpdateCustomerDefaultSourceAsync {
            get {
                return ResourceManager.GetString("CustomersController_Error_UpdateCustomerDefaultSourceAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CustomersController_Error_UpdateCustomerShippingAddressAsync {
            get {
                return ResourceManager.GetString("CustomersController_Error_UpdateCustomerShippingAddressAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserAccountController_BadRequest_AddFundsAsync {
            get {
                return ResourceManager.GetString("UserAccountController_BadRequest_AddFundsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something failed while trying to buy coins for user &apos;{0}&apos;..
        /// </summary>
        internal static string UserAccountController_BadRequest_BuyTokensAsync {
            get {
                return ResourceManager.GetString("UserAccountController_BadRequest_BuyTokensAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something failed while attempting to fetch user &apos;{0}&apos;..
        /// </summary>
        internal static string UserAccountController_BadRequest_FindUserWalletAsync {
            get {
                return ResourceManager.GetString("UserAccountController_BadRequest_FindUserWalletAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserAccountController_BadRequest_WithdrawalAsync {
            get {
                return ResourceManager.GetString("UserAccountController_BadRequest_WithdrawalAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserAccountController_Error_AddFundsAsync {
            get {
                return ResourceManager.GetString("UserAccountController_Error_AddFundsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something failed while trying to buy coins for user &apos;{0}&apos;..
        /// </summary>
        internal static string UserAccountController_Error_BuyTokensAsync {
            get {
                return ResourceManager.GetString("UserAccountController_Error_BuyTokensAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something failed while attempting to fetch user &apos;{0}&apos;..
        /// </summary>
        internal static string UserAccountController_Error_FindUserWalletAsync {
            get {
                return ResourceManager.GetString("UserAccountController_Error_FindUserWalletAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserAccountController_Error_WithdrawalAsync {
            get {
                return ResourceManager.GetString("UserAccountController_Error_WithdrawalAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserAccountController_NotFound_AddFundsAsync {
            get {
                return ResourceManager.GetString("UserAccountController_NotFound_AddFundsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserAccountController_NotFound_BuyTokensAsync {
            get {
                return ResourceManager.GetString("UserAccountController_NotFound_BuyTokensAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserAccountController_NotFound_FindUserWalletAsync {
            get {
                return ResourceManager.GetString("UserAccountController_NotFound_FindUserWalletAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserAccountController_Ok_AddFundsAsync {
            get {
                return ResourceManager.GetString("UserAccountController_Ok_AddFundsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserAccountController_Ok_BuyTokensAsync {
            get {
                return ResourceManager.GetString("UserAccountController_Ok_BuyTokensAsync", resourceCulture);
            }
        }
    }
}
