// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

using eDoxa.Payment.Infrastructure;

namespace eDoxa.Payment.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    internal class PaymentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eDoxa.Payment.Domain.Models.StripeReference", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<string>("ConnectAccountId")
                        .IsRequired();

                    b.Property<string>("CustomerId")
                        .IsRequired();

                    b.HasKey("UserId");

                    b.ToTable("StripeReference");
                });
#pragma warning restore 612, 618
        }
    }
}
