export type LoadPaymentMethodsActionType = "LOAD_PAYMENTMETHODS" | "LOAD_PAYMENTMETHODS_SUCCESS" | "LOAD_PAYMENTMETHODS_FAIL";
export type AttachPaymentMethodActionType = "ATTACH_PAYMENTMETHOD" | "ATTACH_PAYMENTMETHOD_SUCCESS" | "ATTACH_PAYMENTMETHOD_FAIL";
export type DetachPaymentMethodActionType = "DETACH_PAYMENTMETHOD" | "DETACH_PAYMENTMETHOD_SUCCESS" | "DETACH_PAYMENTMETHOD_FAIL";
export type UpdatePaymentMethodActionType = "UPDATE_PAYMENTMETHOD" | "UPDATE_PAYMENTMETHOD_SUCCESS" | "UPDATE_PAYMENTMETHOD_FAIL";
export type LoadBankAccountsActionType = "LOAD_BANK_ACCOUNTS" | "LOAD_BANK_ACCOUNTS_SUCCESS" | "LOAD_BANK_ACCOUNTS_FAIL";
export type CreateBankAccountActionType = "CREATE_BANK_ACCOUNT" | "CREATE_BANK_ACCOUNT_SUCCESS" | "CREATE_BANK_ACCOUNT_FAIL";
export type UpdateBankAccountActionType = "UPDATE_BANK_ACCOUNT" | "UPDATE_BANK_ACCOUNT_SUCCESS" | "UPDATE_BANK_ACCOUNT_FAIL";
export type DeleteBankAccountActionType = "DELETE_BANK_ACCOUNT" | "DELETE_BANK_ACCOUNT_SUCCESS" | "DELETE_BANK_ACCOUNT_FAIL";
