// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eDoxa.Games.Infrastructure;

namespace eDoxa.Games.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(GamesDbContext))]
    [Migration("20191103210332_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eDoxa.Games.Domain.AggregateModels.CredentialAggregate.Credential", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<int>("Game");

                    b.Property<string>("PlayerId")
                        .IsRequired();

                    b.Property<long>("Timestamp");

                    b.HasKey("UserId", "Game");

                    b.HasIndex("Game", "PlayerId")
                        .IsUnique();

                    b.ToTable("Credential");
                });
#pragma warning restore 612, 618
        }
    }
}
