apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "subchart.configmap.fullname" . }}
  labels:
{{ include "subchart.labels" . | indent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.global.infrastructure.aspnetcore.environment }}
  ASPNETCORE_URLS: {{ .Values.global.infrastructure.aspnetcore.urls }}
  ApplicationInsights__InstrumentationKey: {{ .Values.global.infrastructure.applicationInsights.instrumentationKey }}
  Authority__PrivateUrl: {{ include "url.internal" (dict "ServiceName" .Values.global.app.service.api.identity "Context" .) }}
  Authority__PublicUrl: {{ include "url.external" (dict "IngressPath" .Values.global.infrastructure.ingress.api.identity "Context" .) }}
  HealthChecks__IdentityUrl: {{ include "url.readiness" (dict "ServiceName" .Values.global.app.service.api.identity "Context" .) }}
  HealthChecks__CashierUrl: {{ include "url.readiness" (dict "ServiceName" .Values.global.app.service.api.cashier "Context" .) }}
  HealthChecks__ArenaChallengesUrl: {{ include "url.readiness" (dict "ServiceName" .Values.global.app.service.api.arenaChallenges "Context" .) }}
  Serilog__Sink__Seq: {{ include "seq" . }}