export const CREATE_PERSONALINFO_FORM = "CREATE_PERSONALINFO_FORM";
export const UPDATE_PERSONALINFO_FORM = "UPDATE_PERSONALINFO_FORM";

export const CHANGE_EMAIL_FORM = "CHANGE_EMAIL_FORM";

export const CREATE_PHONENUMBER_FORM = "CREATE_PHONENUMBER_FORM";
export const UPDATE_PHONENUMBER_FORM = "UPDATE_PHONENUMBER_FORM";

export const CHANGE_DOXATAG_FORM = "CHANGE_DOXATAG_FORM";

export const CREATE_ADDRESS_FORM = "CREATE_ADDRESS_FORM";
export const UPDATE_ADDRESS_FORM = "UPDATE_ADDRESS_FORM";
export const DELETE_ADDRESS_FORM = "DELETE_ADDRESS_FORM";

export const RESET_PASSWORD_FORM = "RESET_PASSWORD_FORM";
export const FORGOT_PASSWORD_FORM = "FORGOT_PASSWORD_FORM";

export const CREATE_PAYMENTMETHOD_FORM = "CREATE_PAYMENTMETHOD_FORM";
export const UPDATE_PAYMENTMETHOD_FORM = "UPDATE_PAYMENTMETHOD_FORM";
export const DELETE_PAYMENTMETHOD_FORM = "DELETE_PAYMENTMETHOD_FORM";

export const UPDATE_BANK_ACCOUNT_FORM = "UPDATE_BANK_ACCOUNT_FORM";

export const DEPOSIT_FORM = "DEPOSIT_FORM";
export const WITHDRAWAL_FORM = "WITHDRAWAL_FORM";

export const CREATE_CLAN_FORM = "CREATE_CLAN_FORM";

export const LEAVE_CLAN_FORM = "LEAVE_CLAN_FORM";
export const KICK_MEMBER_CLAN_FORM = "KICK_MEMBER_CLAN_FORM";

export const UPLOAD_CLAN_LOGO_FORM = "UPLOAD_CLAN_LOGO_FORM";

export const CREATE_CANDIDATURE_FORM = "CREATE_CANDIDATURE_FORM";
export const ACCEPT_CANDIDATURE_FORM = "ACCEPT_CANDIDATURE_FORM";
export const DECLINE_CANDIDATURE_FORM = "DECLINE_CANDIDATURE_FORM";

export const CREATE_INVITATION_FORM = "CREATE_INVITATION_FORM";
export const ACCEPT_INVITATION_FORM = "ACCEPT_INVITATION_FORM";
export const DECLINE_INVITATION_FORM = "DECLINE_INVITATION_FORM";
