export const CREATE_PERSONALINFO_FORM = "CREATE_PERSONALINFO_FORM";
export const UPDATE_PERSONALINFO_FORM = "UPDATE_PERSONALINFO_FORM";

export const CHANGE_EMAIL_FORM = "CHANGE_EMAIL_FORM";

export const CREATE_PHONENUMBER_FORM = "CREATE_PHONENUMBER_FORM";
export const UPDATE_PHONENUMBER_FORM = "UPDATE_PHONENUMBER_FORM";

export const CHANGE_DOXATAG_FORM = "CHANGE_DOXATAG_FORM";

export const CREATE_ADDRESS_FORM = "CREATE_ADDRESS_FORM";
export const UPDATE_ADDRESS_FORM = "UPDATE_ADDRESS_FORM";
export const DELETE_ADDRESS_FORM = "DELETE_ADDRESS_FORM";

export const RESET_PASSWORD_FORM = "RESET_PASSWORD_FORM";
export const FORGOT_PASSWORD_FORM = "FORGOT_PASSWORD_FORM";

export const CREATE_CREDITCARD_FORM = "CREATE_CREDITCARD_FORM";
export const UPDATE_CREDITCARD_FORM = "UPDATE_CREDITCARD_FORM";
export const DELETE_CREDITCARD_FORM = "DELETE_CREDITCARD_FORM";

export const CREATE_BANK_FORM = "CREATE_CREDITCARD_FORM";
export const UPDATE_BANK_FORM = "UPDATE_BANK_FORM";
export const DELETE_BANK_FORM = "DELETE_BANK_FORM";
