// Identity
export const UPDATE_DOXATAG_FORM = "UPDATE_DOXATAG_FORM";

export const CREATE_INFORMATION_FORM = "CREATE_INFORMATION_FORM";
export const UPDATE_INFORMATION_FORM = "UPDATE_INFORMATION_FORM";

export const UPDATE_EMAIL_FORM = "UPDATE_EMAIL_FORM";

export const CREATE_ADDRESS_FORM = "CREATE_ADDRESS_FORM";
export const UPDATE_ADDRESS_FORM = "UPDATE_ADDRESS_FORM";
export const DELETE_ADDRESS_FORM = "DELETE_ADDRESS_FORM";

export const UPDATE_USER_PHONE_FORM = "UPDATE_USER_PHONE_FORM";

export const RESET_PASSWORD_FORM = "RESET_PASSWORD_FORM";
export const FORGOT_PASSWORD_FORM = "FORGOT_PASSWORD_FORM";

// Payment
export const CREATE_STRIPE_PAYMENTMETHOD_FORM = "CREATE_STRIPE_PAYMENTMETHOD_FORM";
export const UPDATE_STRIPE_PAYMENTMETHOD_FORM = "UPDATE_STRIPE_PAYMENTMETHOD_FORM";
export const DELETE_STRIPE_PAYMENTMETHOD_FORM = "DELETE_STRIPE_PAYMENTMETHOD_FORM";

export const UPDATE_STRIPE_BANKACCOUNT_FORM = "UPDATE_STRIPE_BANKACCOUNT_FORM";

// Cashier
export const DEPOSIT_FORM = "DEPOSIT_FORM";
export const WITHDRAWAL_FORM = "WITHDRAWAL_FORM";

// Clan
export const CREATE_CLAN_FORM = "CREATE_CLAN_FORM";

export const LEAVE_CLAN_FORM = "LEAVE_CLAN_FORM";
export const KICK_CLAN_MEMBER_FORM = "KICK_CLAN_MEMBER_FORM";

export const UPLOAD_CLAN_LOGO_FORM = "UPLOAD_CLAN_LOGO_FORM";

export const CREATE_CANDIDATURE_FORM = "CREATE_CANDIDATURE_FORM";
export const ACCEPT_CANDIDATURE_FORM = "ACCEPT_CANDIDATURE_FORM";
export const DECLINE_CANDIDATURE_FORM = "DECLINE_CANDIDATURE_FORM";

export const CREATE_INVITATION_FORM = "CREATE_INVITATION_FORM";
export const ACCEPT_INVITATION_FORM = "ACCEPT_INVITATION_FORM";
export const DECLINE_INVITATION_FORM = "DECLINE_INVITATION_FORM";
