const keys: any = window;

const {
  REACT_APP_AUTHORITY,
  REACT_APP_CASHIER_WEB_GATEWAY_URL,
  REACT_APP_CHALLENGES_WEB_GATEWAY_URL,
  REACT_APP_WEB_SPA,
  REACT_APP_BETA_ALERT_DISPLAYED,
  REACT_APP_DEPOSIT_BUTTON_DISABLED,
  REACT_APP_WITHDRAW_BUTTON_DISABLED,
  REACT_APP_BUY_BUTTON_DISABLED,
  REACT_APP_FACEBOOK_MCC_ENABLED,
  REACT_APP_FACEBOOK_URL,
  REACT_APP_TWITTER_URL,
  REACT_APP_DISCORD_URL,
  REACT_APP_LINKEDIN_URL,
  REACT_APP_INSTAGRAM_URL,
  REACT_APP_SUPPORT_EMAILADDRESS
} = keys._env_;

export {
  REACT_APP_AUTHORITY,
  REACT_APP_CASHIER_WEB_GATEWAY_URL,
  REACT_APP_CHALLENGES_WEB_GATEWAY_URL,
  REACT_APP_WEB_SPA,
  REACT_APP_BETA_ALERT_DISPLAYED,
  REACT_APP_DEPOSIT_BUTTON_DISABLED,
  REACT_APP_WITHDRAW_BUTTON_DISABLED,
  REACT_APP_BUY_BUTTON_DISABLED,
  REACT_APP_FACEBOOK_MCC_ENABLED,
  REACT_APP_FACEBOOK_URL,
  REACT_APP_TWITTER_URL,
  REACT_APP_DISCORD_URL,
  REACT_APP_LINKEDIN_URL,
  REACT_APP_INSTAGRAM_URL,
  REACT_APP_SUPPORT_EMAILADDRESS
};
