const keys: any = window;

const {
  REACT_APP_WEB_SPA,
  REACT_APP_AUTHORITY,
  REACT_APP_CLIENT_ID,
  REACT_APP_RESPONSE_TYPE,
  REACT_APP_SCOPE,
  REACT_APP_CHALLENGES_WEB_GATEWAY_URL,
  REACT_APP_STRIPE_APIKEYS_PUBLISHABLEKEY
} = keys._env_;

export {
  REACT_APP_WEB_SPA,
  REACT_APP_AUTHORITY,
  REACT_APP_CLIENT_ID,
  REACT_APP_RESPONSE_TYPE,
  REACT_APP_SCOPE,
  REACT_APP_CHALLENGES_WEB_GATEWAY_URL,
  REACT_APP_STRIPE_APIKEYS_PUBLISHABLEKEY
};
