const keys: any = window;

const {
  REACT_APP_AUTHORITY,
  REACT_APP_CASHIER_WEB_GATEWAY_URL,
  REACT_APP_CHALLENGES_WEB_GATEWAY_URL,
  REACT_APP_WEB_SPA
} = keys._env_;

export {
  REACT_APP_AUTHORITY,
  REACT_APP_CASHIER_WEB_GATEWAY_URL,
  REACT_APP_CHALLENGES_WEB_GATEWAY_URL,
  REACT_APP_WEB_SPA
};
