// Identity
export const CREATE_ADDRESS_MODAL = "CREATE_ADDRESS_MODAL";

// Payment
export const CREATE_STRIPE_PAYMENTMETHOD_MODAL = "CREATE_STRIPE_PAYMENTMETHOD_MODAL";
export const UPDATE_STRIPE_PAYMENTMETHOD_MODAL = "UPDATE_STRIPE_PAYMENTMETHOD_MODAL";
export const DELETE_STRIPE_PAYMENTMETHOD_MODAL = "DELETE_STRIPE_PAYMENTMETHOD_MODAL";

export const UPDATE_STRIPE_BANKACCOUNT_MODAL = "UPDATE_STRIPE_BANKACCOUNT_MODAL";

// Cashier
export const DEPOSIT_MODAL = "DEPOSIT_MODAL";
export const WITHDRAWAL_MODAL = "WITHDRAWAL_MODAL";

// Clan
export const CREATE_CLAN_MODAL = "CREATE_CLAN_MODAL";

// Challenge
export const MATCH_SCORE_MODAL = "MATCH_SCORE_MODAL";
