// Arena
export const MATCH_SCORE_MODAL = "MATCH_SCORE_MODAL";

// User
export const CREATE_ADDRESS_MODAL = "CREATE_ADDRESS_MODAL";
export const DEPOSIT_MODAL = "DEPOSIT_MODAL";
export const WITHDRAWAL_MODAL = "WITHDRAWAL_MODAL";

//Stripe
export const UPDATE_BANKACCOUNT_MODAL = "UPDATE_BANKACCOUNT_MODAL";
export const CREATE_PAYMENTMETHOD_MODAL = "CREATE_PAYMENTMETHOD_MODAL";
export const UPDATE_PAYMENTMETHOD_MODAL = "UPDATE_PAYMENTMETHOD_MODAL";
export const DELETE_PAYMENTMETHOD_MODAL = "DELETE_PAYMENTMETHOD_MODAL";

//Organizations
export const CREATE_CLAN_MODAL = "CREATE_CLAN_MODAL";
