// Arena
export const ARENA_CHALLENGE_PARTICIPANT_MATCH_SCORE_DETAILS_MODAL = "ARENA_CHALLENGE_PARTICIPANT_MATCH_SCORE_DETAILS_MODAL";

// User
export const CREATE_ADDRESS_MODAL = "CREATE_ADDRESS_MODAL";

//Stripe
export const CREATE_CREDITCARD_MODAL = "CREATE_CREDITCARD_MODAL";
export const CREATE_BANK_MODAL = "CREATE_BANK_MODAL";
