// Arena
export const ARENA_CHALLENGE_PARTICIPANT_MATCH_SCORE_DETAILS_MODAL = "ARENA_CHALLENGE_PARTICIPANT_MATCH_SCORE_DETAILS_MODAL";

// User
export const CREATE_ADDRESS_MODAL = "CREATE_ADDRESS_MODAL";

//Stripe
export const CREATE_PAYMENTMETHOD_MODAL = "CREATE_PAYMENTMETHOD_MODAL";
export const UPDATE_PAYMENTMETHOD_MODAL = "UPDATE_PAYMENTMETHOD_MODAL";
export const DELETE_PAYMENTMETHOD_MODAL = "DELETE_PAYMENTMETHOD_MODAL";
export const CREATE_BANK_ACCOUNT_MODAL = "CREATE_BANK_ACCOUNT_MODAL";
