// Identity
export const CREATE_USER_ADDRESS_MODAL = "CREATE_USER_ADDRESS_MODAL";

// Payment
export const CREATE_STRIPE_PAYMENTMETHOD_MODAL =
  "CREATE_STRIPE_PAYMENTMETHOD_MODAL";
export const UPDATE_STRIPE_PAYMENTMETHOD_MODAL =
  "UPDATE_STRIPE_PAYMENTMETHOD_MODAL";
export const DELETE_STRIPE_PAYMENTMETHOD_MODAL =
  "DELETE_STRIPE_PAYMENTMETHOD_MODAL";

// Cashier
export const DEPOSIT_MODAL = "DEPOSIT_MODAL";
export const WITHDRAWAL_MODAL = "WITHDRAWAL_MODAL";

// Clan
export const CREATE_CLAN_MODAL = "CREATE_CLAN_MODAL";

// Challenge
export const CHALLENGE_MATCH_SCORE_MODAL = "CHALLENGE_MATCH_SCORE_MODAL";

// Game
export const LINK_GAME_ACCOUNT_CREDENTIAL_MODAL =
  "LINK_GAME_ACCOUNT_CREDENTIAL_MODAL";
export const UNLINK_GAME_ACCOUNT_CREDENTIAL_MODAL =
  "UNLINK_GAME_ACCOUNT_CREDENTIAL_MODAL";
