// Arena
export const ARENA_CHALLENGE_PARTICIPANT_MATCH_SCORE_DETAILS_MODAL = "ARENA_CHALLENGE_PARTICIPANT_MATCH_SCORE_DETAILS_MODAL";

// User
export const CREATE_ADDRESS_MODAL = "CREATE_ADDRESS_MODAL";
