import {
  LOAD_USER_ACCOUNT_BALANCE_MONEY,
  LOAD_USER_ACCOUNT_BALANCE_MONEY_SUCCESS,
  LOAD_USER_ACCOUNT_BALANCE_MONEY_FAIL,
  LOAD_USER_ACCOUNT_BALANCE_TOKEN,
  LOAD_USER_ACCOUNT_BALANCE_TOKEN_SUCCESS,
  LOAD_USER_ACCOUNT_BALANCE_TOKEN_FAIL,
  LOAD_USER_ACCOUNT_TRANSACTIONS,
  LOAD_USER_ACCOUNT_TRANSACTIONS_SUCCESS,
  LOAD_USER_ACCOUNT_TRANSACTIONS_FAIL
} from "./creators";

export default {
    LOAD_USER_ACCOUNT_BALANCE_MONEY,
    LOAD_USER_ACCOUNT_BALANCE_MONEY_SUCCESS,
    LOAD_USER_ACCOUNT_BALANCE_MONEY_FAIL,
    LOAD_USER_ACCOUNT_BALANCE_TOKEN,
    LOAD_USER_ACCOUNT_BALANCE_TOKEN_SUCCESS,
    LOAD_USER_ACCOUNT_BALANCE_TOKEN_FAIL,
    LOAD_USER_ACCOUNT_TRANSACTIONS,
    LOAD_USER_ACCOUNT_TRANSACTIONS_SUCCESS,
    LOAD_USER_ACCOUNT_TRANSACTIONS_FAIL
};
