apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "subchart.configmap.fullname" . }}
  labels:
{{ include "subchart.labels" . | indent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.global.infrastructure.aspnetcore.environment }}
  ASPNETCORE_URLS: {{ .Values.global.infrastructure.aspnetcore.urls }}
  ASPNETCORE_PATH_BASE: {{ include "basePath" .Values.global.app.service.api.payment }}
  ApplicationInsights__InstrumentationKey: {{ .Values.global.infrastructure.applicationInsights.instrumentationKey }}
  AzureKeyVault__Name: {{ .Values.global.infrastructure.azureKeyVault.name }}
  AzureKeyVault__ClientId: {{ .Values.global.infrastructure.azureKeyVault.clientId }}
  AzureKeyVault__ClientSecret: {{ .Values.global.infrastructure.azureKeyVault.clientSecret }}
  AzureServiceBusEnabled: {{ .Values.global.infrastructure.azureServiceBus.enabled }}
  ServiceBus__HostName: {{ .Values.global.infrastructure.azureServiceBus.hostName }}
  ServiceBus__SubscriptionName: {{ .Values.serviceBus.subscriptionName }}
  Serilog__Sink__Seq: {{ include "seq" . }}