{{- if .Values.ingress.enabled -}}
{{- $fullName := include "subchart.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "subchart.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
        - {{ .Values.global.app.host }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.global.app.host }}
      http:
        paths:
        - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
{{- end }}
