import { LOAD_LEAGUEOFLEGENDS_SUMMONERS_BY_NAME, LOAD_LEAGUEOFLEGENDS_SUMMONERS_BY_NAME_SUCCESS, LOAD_LEAGUEOFLEGENDS_SUMMONERS_BY_NAME_FAIL } from "./creators";

export default {
  LOAD_LEAGUEOFLEGENDS_SUMMONERS_BY_NAME,
  LOAD_LEAGUEOFLEGENDS_SUMMONERS_BY_NAME_SUCCESS,
  LOAD_LEAGUEOFLEGENDS_SUMMONERS_BY_NAME_FAIL
};
