import { LOAD_CHALLENGE, LOAD_CHALLENGE_SUCCESS, LOAD_CHALLENGE_FAIL, LOAD_CHALLENGES, LOAD_CHALLENGES_SUCCESS, LOAD_CHALLENGES_FAIL } from "./creators";

export default {
  LOAD_CHALLENGE,
  LOAD_CHALLENGE_FAIL,
  LOAD_CHALLENGE_SUCCESS,
  LOAD_CHALLENGES,
  LOAD_CHALLENGES_SUCCESS,
  LOAD_CHALLENGES_FAIL
};
