# https://mherman.org/blog/dockerizing-a-react-app/
# build environment
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base
WORKDIR /app

FROM node:12.2.0-alpine as node-build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY /src/eDoxa.Web.Spa/ClientApp/package.json /app/package.json
RUN npm install npm -g --silent
RUN npm install react-scripts -g --silent
RUN npm install typesync -g --silent
RUN typesync
RUN npm install --silent
COPY /src/eDoxa.Web.Spa/ClientApp /app
RUN npm run build

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build
WORKDIR /tmp

COPY eDoxa.sln .
COPY docker-compose.dcproj .
COPY src/eDoxa.Cashier.Api/eDoxa.Cashier.Api.csproj ./src/eDoxa.Cashier.Api/
COPY src/eDoxa.Cashier.Domain/eDoxa.Cashier.Domain.csproj ./src/eDoxa.Cashier.Domain/
COPY src/eDoxa.Cashier.Infrastructure/eDoxa.Cashier.Infrastructure.csproj ./src/eDoxa.Cashier.Infrastructure/
COPY src/eDoxa.Cashier.Requests/eDoxa.Cashier.Requests.csproj ./src/eDoxa.Cashier.Requests/
COPY src/eDoxa.Cashier.Responses/eDoxa.Cashier.Responses.csproj ./src/eDoxa.Cashier.Responses/
COPY src/eDoxa.Challenges.Aggregator/eDoxa.Challenges.Aggregator.csproj ./src/eDoxa.Challenges.Aggregator/
COPY src/eDoxa.Challenges.Api/eDoxa.Challenges.Api.csproj src/eDoxa.Challenges.Api/
COPY src/eDoxa.Challenges.BackgroundTasks/eDoxa.Challenges.BackgroundTasks.csproj ./src/eDoxa.Challenges.BackgroundTasks/
COPY src/eDoxa.Challenges.Domain/eDoxa.Challenges.Domain.csproj ./src/eDoxa.Challenges.Domain/
COPY src/eDoxa.Challenges.Infrastructure/eDoxa.Challenges.Infrastructure.csproj ./src/eDoxa.Challenges.Infrastructure/
COPY src/eDoxa.Challenges.Requests/eDoxa.Challenges.Requests.csproj ./src/eDoxa.Challenges.Requests/
COPY src/eDoxa.Challenges.Responses/eDoxa.Challenges.Responses.csproj ./src/eDoxa.Challenges.Responses/
COPY src/eDoxa.Clans.Api/eDoxa.Clans.Api.csproj ./src/eDoxa.Clans.Api/
COPY src/eDoxa.Clans.Domain/eDoxa.Clans.Domain.csproj ./src/eDoxa.Clans.Domain/
COPY src/eDoxa.Clans.Infrastructure/eDoxa.Clans.Infrastructure.csproj ./src/eDoxa.Clans.Infrastructure/
COPY src/eDoxa.Games/eDoxa.Games.csproj ./src/eDoxa.Games/
COPY src/eDoxa.Games.Abstractions/eDoxa.Games.Abstractions.csproj ./src/eDoxa.Games.Abstractions/
COPY src/eDoxa.Games.Api/eDoxa.Games.Api.csproj ./src/eDoxa.Games.Api/
COPY src/eDoxa.Games.Domain/eDoxa.Games.Domain.csproj ./src/eDoxa.Games.Domain/
COPY src/eDoxa.Games.Infrastructure/eDoxa.Games.Infrastructure.csproj ./src/eDoxa.Games.Infrastructure/
COPY src/eDoxa.Games.LeagueOfLegends/eDoxa.Games.LeagueOfLegends.csproj ./src/eDoxa.Games.LeagueOfLegends/
COPY src/eDoxa.Gateway/eDoxa.Gateway.csproj ./src/eDoxa.Gateway/
COPY src/eDoxa.Identity.Api/eDoxa.Identity.Api.csproj ./src/eDoxa.Identity.Api/
COPY src/eDoxa.Identity.Responses/eDoxa.Identity.Responses.csproj ./src/eDoxa.Identity.Responses/
COPY src/eDoxa.Notifications.Api/eDoxa.Notifications.Api.csproj ./src/eDoxa.Notifications.Api/
COPY src/eDoxa.Notifications.Domain/eDoxa.Notifications.Domain.csproj ./src/eDoxa.Notifications.Domain/
COPY src/eDoxa.Notifications.Infrastructure/eDoxa.Notifications.Infrastructure.csproj ./src/eDoxa.Notifications.Infrastructure/
COPY src/eDoxa.Payment.Api/eDoxa.Payment.Api.csproj ./src/eDoxa.Payment.Api/
COPY src/eDoxa.Payment.Domain/eDoxa.Payment.Domain.csproj ./src/eDoxa.Payment.Domain/
COPY src/eDoxa.Payment.Infrastructure/eDoxa.Payment.Infrastructure.csproj ./src/eDoxa.Payment.Infrastructure/
COPY src/eDoxa.Seedwork.Application/eDoxa.Seedwork.Application.csproj ./src/eDoxa.Seedwork.Application/
COPY src/eDoxa.Seedwork.Domain/eDoxa.Seedwork.Domain.csproj ./src/eDoxa.Seedwork.Domain/
COPY src/eDoxa.Seedwork.Infrastructure/eDoxa.Seedwork.Infrastructure.csproj ./src/eDoxa.Seedwork.Infrastructure/
COPY src/eDoxa.Seedwork.Monitoring/eDoxa.Seedwork.Monitoring.csproj ./src/eDoxa.Seedwork.Monitoring/
COPY src/eDoxa.Seedwork.Security/eDoxa.Seedwork.Security.csproj ./src/eDoxa.Seedwork.Security/
COPY src/eDoxa.Web.Spa/eDoxa.Web.Spa.csproj ./src/eDoxa.Web.Spa/
COPY src/eDoxa.Web.Status/eDoxa.Web.Status.csproj ./src/eDoxa.Web.Status/
COPY test/eDoxa.Cashier.IntegrationTests/eDoxa.Cashier.IntegrationTests.csproj ./test/eDoxa.Cashier.IntegrationTests/
COPY test/eDoxa.Cashier.TestHelper/eDoxa.Cashier.TestHelper.csproj ./test/eDoxa.Cashier.TestHelper/
COPY test/eDoxa.Cashier.UnitTests/eDoxa.Cashier.UnitTests.csproj ./test/eDoxa.Cashier.UnitTests/
COPY test/eDoxa.Challenges.IntegrationTests/eDoxa.Challenges.IntegrationTests.csproj ./test/eDoxa.Challenges.IntegrationTests/
COPY test/eDoxa.Challenges.TestHelper/eDoxa.Challenges.TestHelper.csproj ./test/eDoxa.Challenges.TestHelper/
COPY test/eDoxa.Challenges.UnitTests/eDoxa.Challenges.UnitTests.csproj ./test/eDoxa.Challenges.UnitTests/
COPY test/eDoxa.Clans.IntegrationTests/eDoxa.Clans.IntegrationTests.csproj ./test/eDoxa.Clans.IntegrationTests/
COPY test/eDoxa.Clans.TestHelper/eDoxa.Clans.TestHelper.csproj ./test/eDoxa.Clans.TestHelper/
COPY test/eDoxa.Clans.UnitTests/eDoxa.Clans.UnitTests.csproj ./test/eDoxa.Clans.UnitTests/
COPY test/eDoxa.Games.IntegrationTests/eDoxa.Games.IntegrationTests.csproj ./test/eDoxa.Games.IntegrationTests/
COPY test/eDoxa.Games.TestHelper/eDoxa.Games.TestHelper.csproj ./test/eDoxa.Games.TestHelper/
COPY test/eDoxa.Games.UnitTests/eDoxa.Games.UnitTests.csproj ./test/eDoxa.Games.UnitTests/
COPY test/eDoxa.Identity.IntegrationTests/eDoxa.Identity.IntegrationTests.csproj ./test/eDoxa.Identity.IntegrationTests/
COPY test/eDoxa.Identity.TestHelper/eDoxa.Identity.TestHelper.csproj ./test/eDoxa.Identity.TestHelper/
COPY test/eDoxa.Identity.UnitTests/eDoxa.Identity.UnitTests.csproj ./test/eDoxa.Identity.UnitTests/
COPY test/eDoxa.Notifications.IntegrationTests/eDoxa.Notifications.IntegrationTests.csproj ./test/eDoxa.Notifications.IntegrationTests/
COPY test/eDoxa.Notifications.TestHelper/eDoxa.Notifications.TestHelper.csproj ./test/eDoxa.Notifications.TestHelper/
COPY test/eDoxa.Notifications.UnitTests/eDoxa.Notifications.UnitTests.csproj ./test/eDoxa.Notifications.UnitTests/
COPY test/eDoxa.Payment.IntegrationTests/eDoxa.Payment.IntegrationTests.csproj ./test/eDoxa.Payment.IntegrationTests/
COPY test/eDoxa.Payment.TestHelper/eDoxa.Payment.TestHelper.csproj ./test/eDoxa.Payment.TestHelper/
COPY test/eDoxa.Payment.UnitTests/eDoxa.Payment.UnitTests.csproj ./test/eDoxa.Payment.UnitTests/
COPY test/eDoxa.Seedwork.TestHelper/eDoxa.Seedwork.TestHelper.csproj ./test/eDoxa.Seedwork.TestHelper/
COPY test/eDoxa.Seedwork.UnitTests/eDoxa.Seedwork.UnitTests.csproj ./test/eDoxa.Seedwork.UnitTests/
COPY test/eDoxa.FunctionalTests/eDoxa.FunctionalTests.csproj ./test/eDoxa.FunctionalTests/

RUN dotnet restore eDoxa.sln

COPY . .
COPY --from=node-build /app/build /tmp/src/eDoxa.Web.Spa/ClientApp/build
WORKDIR /tmp/src/eDoxa.Web.Spa
RUN dotnet publish -c Release -o /app

FROM build AS publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "eDoxa.Web.Spa.dll"]

EXPOSE 80