apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: edoxa-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - edoxa.gg
    - dev.edoxa.gg
    - test.edoxa.gg 
    - stage.edoxa.gg