apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: telemetry-gw-cert
  namespace: istio-system
spec:
  secretName: telemetry-gw-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "telemetry.edoxa.gg"
  dnsNames:
    - "telemetry.edoxa.gg"
  acme:
    config:
      - http01:
          ingressClass: istio
        domains:
          - "telemetry.edoxa.gg"
