// Identity
export const UPDATE_USER_DOXATAG_FORM = "UPDATE_USER_DOXATAG_FORM";

export const CREATE_USER_PROFILE_FORM = "CREATE_USER_PROFILE_FORM";
export const UPDATE_USER_PROFILE_FORM = "UPDATE_USER_PROFILE_FORM";

export const UPDATE_USER_EMAIL_FORM = "UPDATE_USER_EMAIL_FORM";

export const CREATE_USER_ADDRESS_FORM = "CREATE_USER_ADDRESS_FORM";
export const UPDATE_USER_ADDRESS_FORM = "UPDATE_USER_ADDRESS_FORM";
export const DELETE_USER_ADDRESS_FORM = "DELETE_USER_ADDRESS_FORM";

export const UPDATE_USER_PHONE_FORM = "UPDATE_USER_PHONE_FORM";

export const RESET_USER_PASSWORD_FORM = "RESET_USER_PASSWORD_FORM";
export const FORGOT_USER_PASSWORD_FORM = "FORGOT_USER_PASSWORD_FORM";

// Game
export const GENERATE_GAME_AUTHENTICATION_FORM =
  "GENERATE_GAME_AUTHENTICATION_FORM";
export const VALIDATE_GAME_AUTHENTICATION_FORM =
  "VALIDATE_GAME_AUTHENTICATION_FORM";
export const UNLINK_GAME_CREDENTIAL_FORM = "UNLINK_GAME_CREDENTIAL_FORM";

// Payment
export const CREATE_STRIPE_PAYMENTMETHOD_FORM =
  "CREATE_STRIPE_PAYMENTMETHOD_FORM";
export const UPDATE_STRIPE_PAYMENTMETHOD_FORM =
  "UPDATE_STRIPE_PAYMENTMETHOD_FORM";
export const DELETE_STRIPE_PAYMENTMETHOD_FORM =
  "DELETE_STRIPE_PAYMENTMETHOD_FORM";

export const UPDATE_STRIPE_BANKACCOUNT_FORM = "UPDATE_STRIPE_BANKACCOUNT_FORM";

// Cashier
export const USER_ACCOUNT_DEPOSIT_FORM = "USER_ACCOUNT_DEPOSIT_FORM";
export const USER_ACCOUNT_WITHDRAWAL_FORM = "USER_ACCOUNT_WITHDRAWAL_FORM";

// Clan
export const CREATE_CLAN_FORM = "CREATE_CLAN_FORM";
export const LEAVE_CLAN_FORM = "LEAVE_CLAN_FORM";

export const UPLOAD_CLAN_LOGO_FORM = "UPLOAD_CLAN_LOGO_FORM";

export const KICK_CLAN_MEMBER_FORM = "KICK_CLAN_MEMBER_FORM";

export const SEND_CANDIDATURE_FORM = "SEND_CANDIDATURE_FORM";
export const ACCEPT_CANDIDATURE_FORM = "ACCEPT_CANDIDATURE_FORM";
export const REFUSE_CANDIDATURE_FORM = "REFUSE_CANDIDATURE_FORM";

export const SEND_INVITATION_FORM = "SEND_INVITATION_FORM";
export const ACCEPT_INVITATION_FORM = "ACCEPT_INVITATION_FORM";
export const DECLINE_INVITATION_FORM = "DECLINE_INVITATION_FORM";

// Challenge
export const REGISTER_CHALLENGE_PARTICIPANT_FROM =
  "REGISTER_CHALLENGE_PARTICIPANT_FROM";
