//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDoxa.Challenges.Api.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eDoxa.Challenges.Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChallengeParticipantsController_BadRequest_FindChallengeParticipantsAsync {
            get {
                return ResourceManager.GetString("ChallengeParticipantsController_BadRequest_FindChallengeParticipantsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChallengeParticipantsController_BadRequest_RegisterChallengeParticipantAsync {
            get {
                return ResourceManager.GetString("ChallengeParticipantsController_BadRequest_RegisterChallengeParticipantAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChallengeParticipantsController_Error_FindChallengeParticipantsAsync {
            get {
                return ResourceManager.GetString("ChallengeParticipantsController_Error_FindChallengeParticipantsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChallengeParticipantsController_Error_RegisterChallengeParticipantAsync {
            get {
                return ResourceManager.GetString("ChallengeParticipantsController_Error_RegisterChallengeParticipantAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChallengeParticipantsController_Ok_RegisterChallengeParticipantAsync {
            get {
                return ResourceManager.GetString("ChallengeParticipantsController_Ok_RegisterChallengeParticipantAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChallengesController_BadRequest_FindChallengeAsync {
            get {
                return ResourceManager.GetString("ChallengesController_BadRequest_FindChallengeAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChallengesController_BadRequest_FindChallengesAsync {
            get {
                return ResourceManager.GetString("ChallengesController_BadRequest_FindChallengesAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChallengesController_Error_FindChallengeAsync {
            get {
                return ResourceManager.GetString("ChallengesController_Error_FindChallengeAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChallengesController_Error_FindChallengesAsync {
            get {
                return ResourceManager.GetString("ChallengesController_Error_FindChallengesAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChallengesController_NotFound_FindChallengeAsync {
            get {
                return ResourceManager.GetString("ChallengesController_NotFound_FindChallengeAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MatchesController_BadRequest_FindMatchAsync {
            get {
                return ResourceManager.GetString("MatchesController_BadRequest_FindMatchAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MatchesController_Error_FindMatchAsync {
            get {
                return ResourceManager.GetString("MatchesController_Error_FindMatchAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MatchesController_NotFound_FindMatchAsync {
            get {
                return ResourceManager.GetString("MatchesController_NotFound_FindMatchAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ParticipantMatchesController_BadRequest_FindParticipantMatchesAsync {
            get {
                return ResourceManager.GetString("ParticipantMatchesController_BadRequest_FindParticipantMatchesAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ParticipantMatchesController_Error_FindParticipantMatchesAsync {
            get {
                return ResourceManager.GetString("ParticipantMatchesController_Error_FindParticipantMatchesAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ParticipantsController_BadRequest_FindParticipantAsync {
            get {
                return ResourceManager.GetString("ParticipantsController_BadRequest_FindParticipantAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ParticipantsController_Error_FindParticipantAsync {
            get {
                return ResourceManager.GetString("ParticipantsController_Error_FindParticipantAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ParticipantsController_NotFound_FindParticipantAsync {
            get {
                return ResourceManager.GetString("ParticipantsController_NotFound_FindParticipantAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsersController_BadRequest_FindUserChallengeHistoryAsync {
            get {
                return ResourceManager.GetString("UsersController_BadRequest_FindUserChallengeHistoryAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsersController_Error_FindUserChallengeHistoryAsync {
            get {
                return ResourceManager.GetString("UsersController_Error_FindUserChallengeHistoryAsync", resourceCulture);
            }
        }
    }
}
